// Contenuto estratto dal vecchio sito: Il Diacono nel Catechismo della Chiesa Cattolica.
export const DIACONO_CATECHISMO = `
<p>1536 L'Ordine è il sacramento grazie al quale la missione affidata da Cristo ai suoi Apostoli continua ad essere esercitata nella Chiesa sino alla fine dei tempi: è, dunque, il sacramento del ministero apostolico. Comporta tre gradi: l'Episcopato, il presbiterato e il diaconato. [Per l'istituzione e la missione del ministero apostolico da parte di Cristo, cf nn. 874-896. Qui si tratta soltanto della via sacramentale attraverso la quale tale ministero viene trasmesso.] I. Perché il nome di sacramento dell'Ordine?</p>
<p>1537 La parola Ordine, nell'antichità romana, designava corpi costituiti in senso civile, soprattutto il corpo di coloro che governano. « Ordinatio » – ordinazione – indica l'integrazione in un « ordo » – ordine –. Nella Chiesa ci sono corpi costituiti che la Tradizione, non senza fondamenti scritturistici, 141 chiama sin dai tempi antichi con il nome di JV&gt;,4H (in greco), di ordines: così la liturgia parla dell'« ordo Episcoporum » – ordine dei Vescovi –, dell'« ordo presbyterorum » – ordine dei presbiteri –, dell'« ordo diaconorum » – ordine dei diaconi. Anche altri gruppi ricevono questo nome di « ordo »: i catecumeni, le vergini, gli sposi, le vedove...</p>
<p>1538 L'integrazione in uno di questi corpi ecclesiali avveniva con un rito chiamato ordinatio, atto religioso e liturgico che consisteva in una consacrazione, una benedizione o un sacramento. Oggi la parola « ordinatio » è riservata all'atto sacramentale che integra nell'ordine dei Vescovi, dei presbiteri e dei diaconi e che va al di là di una semplice elezione, designazione, delega o istituzione da parte della comunità, poiché conferisce un dono dello Spirito Santo che permette di esercitare una potestà sacra (« sacra potestas »), 142 la quale non può venire che da Cristo stesso, mediante la sua Chiesa. L'ordinazione è chiamata anche « consecratio » – consacrazione – poiché è una separazione e una investitura da parte di Cristo stesso, per la sua Chiesa. L'imposizione delle mani del Vescovo, insieme con la preghiera consacratoria, costituisce il segno visibile di tale consacrazione. II. Il sacramento dell'Ordine nell'Economia della salvezza Il sacerdozio dell'Antica Alleanza</p>
<p>1539 Il popolo eletto fu costituito da Dio come « un regno di sacerdoti e una nazione santa » (Es 19,6).</p>
<p>143 Ma, all'interno del popolo di Israele, Dio scelse una delle dodici tribù, quella di Levi, riservandola per il servizio liturgico;</p>
<p>144 Dio stesso è la sua parte di eredità.</p>
<p>145 Un rito proprio ha consacrato le origini del sacerdozio dell'Antica Alleanza.</p>
<p>146 In essa i sacerdoti sono costituiti « per il bene degli uomini nelle cose che riguardano Dio, per offrire doni e sacrifici per i peccati »</p>
<p>1540 Istituito per annunciare la parola di Dio 148 e per ristabilire la comunione con Dio mediante i sacrifici e la preghiera, tale sacerdozio resta tuttavia impotente a operare la salvezza, avendo bisogno di offrire continuamente sacrifici e non potendo portare ad una santificazione definitiva, 149 che soltanto il sacrificio di Cristo avrebbe operato.</p>
<p>1541 La liturgia della Chiesa vede tuttavia nel sacerdozio di Aronne e nel servizio dei leviti, come pure nell'istituzione dei settanta « Anziani », 150 prefigurazioni del ministero ordinato della Nuova Alleanza. Così, nel rito latino, la Chiesa si esprime nella preghiera consacratoria dell'ordinazione dei Vescovi: « O Dio, Padre del Signore nostro Gesù Cristo, [...] con la parola di salvezza hai dato norme di vita nella tua Chiesa: tu, dal principio, hai eletto Abramo come padre dei giusti, hai costituito capi e sacerdoti per non lasciare mai senza ministero il tuo santuario... »</p>
<p>1542 Nell'ordinazione dei sacerdoti, la Chiesa prega: « Signore, Padre santo, [...] nell'Antica Alleanza presero forma e figura vari uffici istituiti per il servizio liturgico. A Mosè e ad Aronne, da te prescelti per reggere e santificare il tuo popolo, associasti collaboratori che li seguivano nel grado e nella dignità. Nel cammino dell'esodo comunicasti a settanta uomini saggi e prudenti lo spirito di Mosè tuo servo [...]. Tu rendesti partecipi i figli di Aronne della pienezza del loro padre »</p>
<p>1543 E nella preghiera consacratoria per l'ordinazione dei diaconi, la Chiesa confessa: « Dio onnipotente, [...] tu hai formato la Chiesa [...]; hai disposto che mediante i tre gradi del ministero da te istituito cresca e si edifichi il nuovo tempio, come in antico scegliesti i figli di Levi a servizio del tabernacolo santo » L'unico sacerdozio di Cristo</p>
<p>1544 Tutte le prefigurazioni del sacerdozio dell'Antica Alleanza trovano il loro compimento in Cristo Gesù, « unico [...] mediatore tra Dio e gli uomini » (1 Tm 2,5). Melchisedek, « sacerdote del Dio altissimo » (Gn 14,18), è considerato dalla Tradizione cristiana come una prefigurazione del sacerdozio di Cristo, unico « sommo sacerdote alla maniera di Melchisedek » (Eb 5,10; 6,20), « santo, innocente, senza macchia » (Eb 7,26), il quale « con un'unica oblazione [...] ha reso perfetti per sempre quelli che vengono santificati » (Eb 10,14), cioè con l'unico sacrificio della sua croce.</p>
<p>1545 Il sacrificio redentore di Cristo è unico, compiuto una volta per tutte. Tuttavia è reso presente nel sacrificio eucaristico della Chiesa. Lo stesso vale per l'unico sacerdozio di Cristo: esso è reso presente dal sacerdozio ministeriale senza che venga diminuita l'unicità del sacerdozio di Cristo. « Infatti solo Cristo è il vero Sacerdote, mentre gli altri sono i suoi ministri » Due partecipazioni all'unico sacerdozio di Cristo</p>
<p>1546 Cristo, Sommo Sacerdote e unico mediatore, ha fatto della Chiesa un regno di sacerdoti per il suo Dio e Padre.</p>
<p>155 Tutta la comunità dei credenti è, come tale, sacerdotale. I fedeli esercitano il loro sacerdozio battesimale attraverso la partecipazione, ciascuno secondo la vocazione sua propria, alla missione di Cristo, Sacerdote, Profeta e Re. È per mezzo dei sacramenti del Battesimo e della Confermazione che i fedeli « vengono consacrati a formare [...] un sacerdozio santo »</p>
<p>1547 Il sacerdozio ministeriale o gerarchico dei Vescovi e dei sacerdoti e il sacerdozio comune di tutti i fedeli, anche se « l'uno e l'altro, ognuno a suo proprio modo, partecipano all'unico sacerdozio di Cristo », 157 differiscono tuttavia essenzialmente, pur essendo « ordinati l'uno all'altro » In che senso? Mentre il sacerdozio comune dei fedeli si realizza nello sviluppo della grazia battesimale – vita di fede, di speranza e di carità, vita secondo lo Spirito –, il sacerdozio ministeriale è al servizio del sacerdozio comune, è relativo allo sviluppo della grazia battesimale di tutti i cristiani. È uno dei mezzi con i quali Cristo continua a costruire e a guidare la sua Chiesa. Proprio per questo motivo viene trasmesso mediante un sacramento specifico, il sacramento dell'Ordine. In persona di Cristo Capo</p>
<p>1548 Nel servizio ecclesiale del ministero ordinato è Cristo stesso che è presente alla sua Chiesa in quanto Capo del suo corpo, Pastore del suo gregge, Sommo Sacerdote del sacrificio redentore, Maestro di verità. È ciò che la Chiesa esprime dicendo che il sacerdote, in virtù del sacramento dell'Ordine, agisce « in persona Christi Capitis » – in persona di Cristo Capo:</p>
<p>159 « È il medesimo Sacerdote, Cristo Gesù, di cui realmente il ministro fa le veci. Costui se, in forza della consacrazione sacerdotale che ha ricevuto, è in verità assimilato al Sommo Sacerdote, gode della potestà di agire con la potenza dello stesso Cristo che rappresenta ('virtute ac persona ipsius Christi') » « Cristo è la fonte di ogni sacerdozio: infatti il sacerdote della Legge [antica] era figura di lui, mentre il sacerdote della nuova Legge agisce in persona di lui »</p>
<p>1549 Attraverso il ministero ordinato, specialmente dei Vescovi e dei sacerdoti, la presenza di Cristo quale Capo della Chiesa è resa visibile in mezzo alla comunità dei credenti.</p>
<p>162 Secondo la bella espressione di sant'Ignazio di Antiochia, il Vescovo è JbB@H J@L() A"JDH, come l'immagine vivente di Dio Padre.</p>
<p>1550 Questa presenza di Cristo nel ministro non deve essere intesa come se costui fosse premunito contro ogni debolezza umana, lo spirito di dominio, gli errori, persino il peccato. La forza dello Spirito Santo non garantisce nello stesso modo tutti gli atti dei ministri. Mentre nell'amministrazione dei sacramenti viene data questa garanzia, così che neppure il peccato del ministro può impedire il frutto della grazia, esistono molti altri atti in cui l'impronta umana del ministro lascia tracce che non sono sempre segno della fedeltà al Vangelo e che di conseguenza possono nuocere alla fecondità apostolica della Chiesa.</p>
<p>1551 Questo sacerdozio è ministeriale. « Questo ufficio che il Signore ha affidato ai Pastori del suo popolo è un vero servizio » Esso è interamente riferito a Cristo e agli uomini. Dipende interamente da Cristo e dal suo unico sacerdozio ed è stato istituito in favore degli uomini e della comunità della Chiesa. Il sacramento dell'Ordine comunica « una potestà sacra », che è precisamente quella di Cristo. L'esercizio di tale autorità deve dunque misurarsi sul modello di Cristo, che per amore si è fatto l'ultimo e il servo di tutti.</p>
<p>165 « Il Signore ha esplicitamente detto che la sollecitudine per il suo gregge era una prova di amore verso di lui » ... «a nome di tutta la Chiesa» Il sacerdozio ministeriale non ha solamente il compito di rappresentare Cristo – Capo della Chiesa – di fronte all'assemblea dei fedeli; esso agisce anche a nome di tutta la Chiesa allorché presenta a Dio la preghiera della Chiesa 167 e soprattutto quando offre il sacrificio eucaristico.</p>
<p>1553 « A nome di tutta la Chiesa ». Ciò non significa che i sacerdoti siano i delegati della comunità. La preghiera e l'offerta della Chiesa sono inseparabili dalla preghiera e dall'offerta di Cristo, suo Capo. È sempre il culto di Cristo nella sua Chiesa e per mezzo di essa. È tutta la Chiesa, corpo di Cristo, che prega e si offre, « per ipsum et cum ipso et in ipso » – per lui, con lui e in lui – nell'unità dello Spirito Santo, a Dio Padre. Tutto il corpo, « Caput et membra » – Capo e membra – prega e si offre; per questo coloro che, nel corpo, sono suoi ministri in senso proprio, vengono chiamati ministri non solo di Cristo, ma anche della Chiesa. Proprio perché rappresenta Cristo, il sacerdozio ministeriale può rappresentare la Chiesa. III. I tre gradi del sacramento dell'Ordine</p>
<p>1554 « Il ministero ecclesiastico di istituzione divina viene esercitato in diversi ordini da quelli che già anticamente sono chiamati Vescovi, presbiteri, diaconi » La dottrina cattolica, espressa nella liturgia, nel Magistero e nella pratica costante della Chiesa, riconosce che esistono due gradi di partecipazione ministeriale al sacerdozio di Cristo: l'Episcopato e il presbiterato. Il diaconato è finalizzato al loro aiuto e al loro servizio. Per questo il termine « sacerdos » – sacerdote – designa, nell'uso attuale, i Vescovi e i presbiteri, ma non i diaconi. Tuttavia, la dottrina cattolica insegna che i gradi di partecipazione sacerdotale (Episcopato e presbiterato) e il grado di servizio (diaconato) sono tutti e tre conferiti da un atto sacramentale chiamato « ordinazione », cioè dal sacramento dell'Ordine: « Tutti rispettino i diaconi come lo stesso Gesù Cristo, e il Vescovo come l'immagine del Padre, e i presbiteri come senato di Dio e come collegio apostolico: senza di loro non c'è Chiesa » L'ordinazione episcopale - pienezza del sacramento dell'Ordine</p>
<p>1555 « Fra i vari ministeri che fin dai primi tempi si esercitano nella Chiesa, secondo la testimonianza della tradizione, tiene il primo posto l'ufficio di quelli che, costituiti nell'Episcopato, per successione che risale all'origine, possiedono i tralci del seme apostolico »</p>
<p>1556 Per adempiere alla loro alta missione, « gli Apostoli sono stati arricchiti da Cristo con una speciale effusione dello Spirito Santo discendente su loro, ed essi stessi, con l'imposizione delle mani, hanno trasmesso questo dono dello Spirito ai loro collaboratori, dono che è stato trasmesso fino a noi nella consacrazione episcopale »</p>
<p>1557 Il Concilio Vaticano II insegna che « con la consacrazione episcopale viene conferita la pienezza del sacramento dell'Ordine, quella cioè che dalla consuetudine liturgica della Chiesa e dalla voce dei santi Padri viene chiamata sommo sacerdozio, vertice ["summa"] del sacro ministero »</p>
<p>1558 « La consacrazione episcopale conferisce pure, con l'ufficio di santificare, gli uffici di insegnare e di governare [...]. Infatti [...] con l'imposizione delle mani e con le parole della consacrazione la grazia dello Spirito Santo viene conferita e viene impresso un sacro carattere, in maniera che i Vescovi, in modo eminente e visibile, sostengano le parti dello stesso Cristo Maestro, Pastore e Pontefice, e agiscano in sua persona ["in Eius persona agant"] » « Perciò i Vescovi, per virtù dello Spirito Santo, che loro è stato dato, sono divenuti veri e autentici Maestri della fede, Pontefici e Pastori »</p>
<p>1559 « Uno viene costituito membro del Corpo episcopale in virtù della consacrazione episcopale e mediante la comunione gerarchica col capo del Collegio e con i membri » Il carattere e la natura collegiale dell'ordine episcopale si manifestano, tra l'altro, nell'antica prassi della Chiesa che per la consacrazione di un nuovo Vescovo vuole la partecipazione di più Vescovi.</p>
<p>177 Per l'ordinazione legittima di un Vescovo, oggi è richiesto un intervento speciale del Vescovo di Roma, per il fatto che egli è il supremo vincolo visibile della comunione delle Chiese particolari nell'unica Chiesa e il garante della loro libertà.</p>
<p>1560 Ogni Vescovo ha, quale vicario di Cristo, l'ufficio pastorale della Chiesa particolare che gli è stata affidata, ma nello stesso tempo porta collegialmente con tutti i fratelli nell'Episcopato la sollecitudine per tutte le Chiese: « Se ogni Vescovo è propriamente Pastore soltanto della porzione del gregge affidata alle sue cure, la sua qualità di legittimo successore degli Apostoli, per istituzione divina, lo rende solidalmente responsabile della missione apostolica della Chiesa »</p>
<p>1561 Quanto è stato detto spiega perché l'Eucaristia celebrata dal Vescovo ha un significato tutto speciale come espressione della Chiesa riunita attorno all'altare sotto la presidenza di colui che rappresenta visibilmente Cristo, Buon Pastore e Capo della sua Chiesa.</p>
<p>179 L'ordinazione dei presbiteri - cooperatori dei Vescovi</p>
<p>1562 « Cristo, consacrato e mandato nel mondo dal Padre, per mezzo dei suoi Apostoli ha reso partecipi della sua consacrazione e della sua missione i loro successori, cioè i Vescovi, i quali hanno legittimamente affidato, secondo diversi gradi, l'ufficio del loro ministero a vari soggetti nella Chiesa » « La [loro] funzione ministeriale fu trasmessa in grado subordinato ai presbiteri, affinché questi, costituiti nell'ordine del presbiterato, fossero cooperatori dell'ordine episcopale, per il retto assolvimento della missione apostolica affidata da Cristo »</p>
<p>1563 « La funzione dei presbiteri, in quanto strettamente unita all'ordine episcopale, partecipa dell'autorità con la quale Cristo stesso fa crescere, santifica e governa il proprio corpo. Per questo motivo, il sacerdozio dei presbiteri, pur presupponendo i sacramenti dell'iniziazione cristiana, viene conferito da quel particolare sacramento per il quale i presbiteri, in virtù dell'unzione dello Spirito Santo, sono segnati da uno speciale carattere che li configura a Cristo Sacerdote, in modo da poter agire in nome e nella persona di Cristo Capo »</p>
<p>1564 « I presbiteri, pur non possedendo il vertice del sacerdozio e dipendendo dai Vescovi nell'esercizio della loro potestà, sono tuttavia a loro uniti nell'onore sacerdotale e in virtù del sacramento dell'Ordine, a immagine di Cristo, Sommo ed eterno Sacerdote, 183 sono consacrati per predicare il Vangelo, pascere i fedeli e celebrare il culto divino, quali veri sacerdoti del Nuovo Testamento »</p>
<p>1565 In virtù del sacramento dell'Ordine i sacerdoti partecipano alla dimensione universale della missione affidata da Cristo agli Apostoli. Il dono spirituale che hanno ricevuto nell'ordinazione non li prepara ad una missione limitata e ristretta, bensì a una vastissima e universale missione di salvezza, « fino agli ultimi confini della terra » (At 1,8),</p>
<p>185 « pronti nel loro animo a predicare dovunque il Vangelo »</p>
<p>1566 Essi « soprattutto esercitano la loro funzione sacra nel culto o assemblea eucaristica, dove, agendo in persona di Cristo, e proclamando il suo mistero, uniscono i voti dei fedeli al sacrificio del loro Capo e nel sacrificio della Messa rendono presente e applicano, fino alla venuta del Signore, l'unico sacrificio del Nuovo Testamento, il sacrificio cioè di Cristo, che una volta per tutte si offre al Padre quale vittima immacolata » Da questo unico sacrificio tutto il loro ministero sacerdotale trae la sua forza.</p>
<p>1567 « I presbiteri, saggi collaboratori dell'ordine episcopale e suo aiuto e strumento, chiamati al servizio del popolo di Dio, costituiscono col loro Vescovo un unico presbiterio, sebbene destinato a uffici diversi. Nelle singole comunità locali di fedeli rendono, per così dire, presente il Vescovo, cui sono uniti con animo fiducioso e grande, condividono in parte le sue funzioni e la sua sollecitudine e le esercitano con dedizione quotidiana » I sacerdoti non possono esercitare il loro ministero se non in dipendenza dal Vescovo e in comunione con lui. La promessa di obbedienza che fanno al Vescovo al momento dell'ordinazione e il bacio di pace del Vescovo al termine della liturgia dell'ordinazione significano che il Vescovo li considera come suoi collaboratori, suoi figli, suoi fratelli e suoi amici, e che, in cambio, essi gli devono amore e obbedienza.</p>
<p>1568 « I presbiteri, costituiti nell'ordine del presbiterato mediante l'ordinazione, sono tutti tra loro uniti da intima fraternità sacramentale; ma in modo speciale essi formano un unico presbiterio nella diocesi al cui servizio sono assegnati sotto il proprio Vescovo » L'unità del presbiterio trova un'espressione liturgica nella consuetudine secondo la quale, durante il rito dell'ordinazione, i presbiteri, dopo il Vescovo, impongono anch'essi le mani. L'ordinazione dei diaconi - « per il servizio » « In un grado inferiore della gerarchia stanno i diaconi, ai quali sono imposte le mani "non per il sacerdozio, ma per il servizio" » Per l'ordinazione al diaconato soltanto il Vescovo impone le mani, significando così che il diacono è legato in modo speciale al Vescovo nei compiti della sua « diaconia »</p>
<p>1570 I diaconi partecipano in una maniera particolare alla missione e alla grazia di Cristo.</p>
<p>193 Il sacramento dell'Ordine imprime in loro un sigillo (« carattere ») che nulla può cancellare e che li configura a Cristo, il quale si è fatto « diacono », cioè servo di tutti.</p>
<p>194 Compete ai diaconi, tra l'altro, assistere il Vescovo e i presbiteri nella celebrazione dei divini misteri, soprattutto dell'Eucaristia, distribuirla, assistere e benedire il Matrimonio, proclamare il Vangelo e predicare, presiedere ai funerali e dedicarsi ai vari servizi della carità.</p>
<p>1571 Dopo il Concilio Vaticano II la Chiesa latina ha ripristinato il diaconato « come un grado proprio e permanente della gerarchia », 196 mentre le Chiese d'Oriente lo avevano sempre conservato. Il diaconato permanente, che può essere conferito a uomini sposati, costituisce un importante arricchimento per la missione della Chiesa. In realtà, è conveniente e utile che gli uomini che nella Chiesa adempiono un ministero veramente diaconale, sia nella vita liturgica e pastorale, sia nelle opere sociali e caritative « siano fortificati per mezzo dell'imposizione delle mani, trasmessa dal tempo degli Apostoli, e siano più strettamente uniti all'altare, per poter esplicare più fruttuosamente il loro ministero con l'aiuto della grazia sacramentale del diaconato » IV. La celebrazione di questo sacramento</p>
<p>1572 La celebrazione dell'ordinazione di un Vescovo, di presbiteri o di diaconi, data la sua importanza per la vita della Chiesa particolare, richiede il concorso del maggior numero possibile di fedeli. Avrà luogo preferibilmente la domenica e nella cattedrale, con quella solennità che si addice alla circostanza. Le tre ordinazioni, del Vescovo, del presbitero, e del diacono, hanno la medesima configurazione. Il loro posto è in seno alla liturgia eucaristica.</p>
<p>1573 Il rito essenziale del sacramento dell'Ordine è costituito, per i tre gradi, dall'imposizione delle mani, da parte del Vescovo, sul capo dell'ordinando come pure dalla specifica preghiera consacratoria che domanda a Dio l'effusione dello Spirito Santo e dei suoi doni adatti al ministero per il quale il candidato viene ordinato.</p>
<p>1574 Come in tutti i sacramenti, accompagnano la celebrazione alcuni riti annessi. Pur variando notevolmente nelle diverse tradizioni liturgiche, essi hanno in comune la proprietà di esprimere i molteplici aspetti della grazia sacramentale. Così, nel rito latino, i riti di introduzione – la presentazione e l'elezione dell'ordinando, l'omelia del Vescovo, l'interrogazione dell'ordinando, le litanie dei santi – attestano che la scelta del candidato è stata fatta in conformità alla prassi della Chiesa e preparano l'atto solenne della consacrazione. A questa fanno seguito altri riti che esprimono e completano in maniera simbolica il mistero che si è compiuto: per il Vescovo e il presbitero l'unzione del santo crisma, segno dell'unzione speciale dello Spirito Santo che rende fecondo il loro ministero; la consegna del libro dei Vangeli, dell'anello, della mitra e del pastorale al Vescovo, come segno della sua missione apostolica di annunziare la Parola di Dio, della sua fedeltà alla Chiesa, Sposa di Cristo, del suo compito di Pastore del gregge del Signore; la consegna, al sacerdote, della patena e del calice, l'offerta del popolo santo, 199 che egli è chiamato a presentare a Dio; la consegna del libro dei Vangeli al diacono, che ha ricevuto la missione di annunziare il Vangelo di Cristo. V. Chi può conferire questo sacramento?</p>
<p>1575 È Cristo che ha scelto gli Apostoli e li ha resi partecipi della sua missione e della sua autorità. Innalzato alla destra del Padre, non abbandona il suo gregge, ma lo custodisce e lo protegge sempre per mezzo degli Apostoli e ancora lo conduce sotto la guida di quegli stessi Pastori che continuano oggi la sua opera.</p>
<p>200 È dunque Cristo che stabilisce alcuni come Apostoli, altri come Pastori.</p>
<p>201 Egli continua ad agire per mezzo dei Vescovi.</p>
<p>1576 Poiché il sacramento dell'Ordine è il sacramento del ministero apostolico, spetta ai Vescovi in quanto successori degli Apostoli trasmettere « questo dono dello Spirito »,</p>
<p>203 « il seme apostolico » I Vescovi validamente ordinati, che sono cioè nella linea della successione apostolica, conferiscono validamente i tre gradi del sacramento dell'Ordine.</p>
<p>205 VI. Chi può ricevere questo sacramento?</p>
<p>1577 « Riceve validamente la sacra ordinazione esclusivamente il battezzato di sesso maschile ["vir"] » Il Signore Gesù ha scelto uomini ["viri"] per formare il collegio dei dodici Apostoli, 207 e gli Apostoli hanno fatto lo stesso quando hanno scelto i collaboratori 208 che sarebbero loro succeduti nel ministero.</p>
<p>209 Il collegio dei Vescovi, con i quali i presbiteri sono uniti nel sacerdozio, rende presente e attualizza fino al ritorno di Cristo il collegio dei Dodici. La Chiesa si riconosce vincolata da questa scelta fatta dal Signore stesso. Per questo motivo l'ordinazione delle donne non è possibile.</p>
<p>1578 Nessuno ha un diritto a ricevere il sacramento dell'Ordine. Infatti nessuno può attribuire a se stesso questo ufficio. Ad esso si è chiamati da Dio.</p>
<p>211 Chi crede di riconoscere i segni della chiamata di Dio al ministero ordinato, deve sottomettere umilmente il proprio desiderio all'autorità della Chiesa, alla quale spetta la responsabilità e il diritto di chiamare qualcuno a ricevere gli Ordini. Come ogni grazia, questo sacramento non può essere ricevuto che come dono immeritato.</p>
<p>1579 Tutti i ministri ordinati della Chiesa latina, ad eccezione dei diaconi permanenti, sono normalmente scelti fra gli uomini credenti che vivono da celibi e che intendono conservare il celibato « per il regno dei cieli » (Mt 19,12). Chiamati a consacrarsi con cuore indiviso al Signore e alle « sue cose », 212 essi si donano interamente a Dio e agli uomini. Il celibato è un segno di questa vita nuova al cui servizio il ministro della Chiesa viene consacrato; abbracciato con cuore gioioso, esso annuncia in modo radioso il regno di Dio.</p>
<p>1580 Nelle Chiese Orientali, da secoli, è in vigore una disciplina diversa: mentre i Vescovi sono scelti unicamente fra coloro che vivono nel celibato, uomini sposati possono essere ordinati diaconi e presbiteri. Tale prassi è da molto tempo considerata come legittima; questi presbiteri esercitano un ministero fruttuoso in seno alle loro comunità.</p>
<p>214 D'altro canto il celibato dei presbiteri è in grande onore nelle Chiese Orientali, e numerosi sono i presbiteri che l'hanno scelto liberamente, per il regno di Dio. In Oriente come in Occidente, chi ha ricevuto il sacramento dell'Ordine non può più sposarsi. VII. Gli effetti del sacramento dell'Ordine Il carattere indelebile</p>
<p>1581 Questo sacramento configura a Cristo in forza di una grazia speciale dello Spirito Santo, allo scopo di servire da strumento di Cristo per la sua Chiesa. Per mezzo dell'ordinazione si viene abilitati ad agire come rappresentanti di Cristo, Capo della Chiesa, nella sua triplice funzione di sacerdote, profeta e re.</p>
<p>1582 Come nel caso del Battesimo e della Confermazione, questa partecipazione alla funzione di Cristo è accordata una volta per tutte. Il sacramento dell'Ordine conferisce, anch'esso, un carattere spirituale indelebile e non può essere ripetuto né essere conferito per un tempo limitato.</p>
<p>1583 Un soggetto validamente ordinato può, certo, per gravi motivi, essere dispensato dagli obblighi e dalle funzioni connessi all'ordinazione o gli può essere fatto divieto di esercitarli, ma non può più ridiventare laico in senso stretto, 216 poiché il carattere impresso dall'ordinazione rimane per sempre.</p>
<p>217 La vocazione e la missione ricevute nel giorno della sua ordinazione lo segnano in modo permanente.</p>
<p>1584 Poiché in definitiva è Cristo che agisce e opera la salvezza mediante il ministro ordinato, l'indegnità di costui non impedisce a Cristo di agire.</p>
<p>218 Sant'Agostino lo dice con forza: « Un ministro superbo va messo assieme al diavolo; ma non per questo viene contaminato il dono di Cristo, che attraverso di lui continua a fluire nella sua purezza e per mezzo di lui arriva limpido a fecondare la terra. [...] La virtù spirituale del sacramento è infatti come la luce: giunge pura a coloro che devono essere illuminati e, anche se deve passare attraverso esseri immondi, non viene contaminata » La grazia dello Spirito Santo</p>
<p>1585 La grazia dello Spirito Santo propria di questo sacramento consiste in una configurazione a Cristo Sacerdote, Maestro e Pastore del quale l'ordinato è costituito ministro.</p>
<p>1586 Per il Vescovo è innanzi tutto una grazia di fortezza (« Il tuo Spirito che regge e guida »: Preghiera consacratoria del Vescovo nel rito latino 220): la grazia di guidare e di difendere con forza e prudenza la sua Chiesa come padre e pastore, con un amore gratuito verso tutti e una predilezione per i poveri, gli ammalati e i bisognosi.</p>
<p>221 Questa grazia lo spinge ad annunciare a tutti il Vangelo, ad essere il modello del suo gregge, a precederlo sul cammino della santificazione identificandosi nell'Eucaristia con Cristo Sacerdote e Vittima, senza temere di dare la vita per le sue pecore: « Concedi, Padre che conosci i cuori, a questo servo che hai scelto per l'Episcopato, di pascere il tuo santo gregge e di esercitare in maniera irreprensibile e in tuo onore la massima dignità sacerdotale, servendoti notte e giorno; di rendere il tuo volto incessantemente propizio e di offrirti i doni della tua santa Chiesa; di avere, in virtù dello spirito del sommo sacerdozio, il potere di rimettere i peccati secondo il tuo comando, di distribuire i compiti secondo la tua volontà e di sciogliere ogni legame in virtù del potere che hai dato agli Apostoli; di esserti accetto per la sua mansuetudine e per la purezza del suo cuore, offrendoti un profumo soave per mezzo di Gesù Cristo tuo Figlio... »</p>
<p>1587 Il dono spirituale conferito dall'ordinazione presbiterale è espresso da questa preghiera propria del rito bizantino. Il Vescovo, imponendo le mani, dice tra l'altro: « Signore, riempi di Spirito Santo colui che ti sei degnato di elevare alla dignità sacerdotale, affinché sia degno di stare irreprensibile davanti al tuo altare, di annunciare il Vangelo del tuo regno, di compiere il ministero della tua parola di verità, di offrirti doni e sacrifici spirituali, di rinnovare il tuo popolo mediante il lavacro della rigenerazione; in modo che egli stesso vada incontro al nostro grande Dio e Salvatore Gesù Cristo, tuo unico Figlio, nel giorno della sua seconda venuta, e riceva dalla tua immensa bontà la ricompensa di un fedele adempimento del suo ministero »</p>
<p>1588 Quanto ai diaconi, « sostenuti dalla grazia sacramentale, servono il popolo di Dio nel ministero della liturgia, della parola e della carità, in comunione con il Vescovo e il suo presbiterio »</p>
<p>1589 Dinanzi alla grandezza della grazia e dell'ufficio sacerdotali, i santi dottori hanno avvertito l'urgente appello alla conversione al fine di corrispondere con tutta la loro vita a colui di cui sono divenuti ministri mediante il sacramento. Così, san Gregorio Nazianzeno, giovanissimo sacerdote, esclama: « Bisogna cominciare col purificare se stessi prima di purificare gli altri; bisogna essere istruiti per poter istruire; bisogna divenire luce per illuminare, avvicinarsi a Dio per avvicinare a lui gli altri, essere santificati per santificare, condurre per mano e consigliare con intelligenza » « So di chi siamo i ministri, a quale altezza ci troviamo e chi è colui verso il quale ci dirigiamo. Conosco la grandezza di Dio e la debolezza dell'uomo, ma anche la sua forza » [Chi è dunque il sacerdote? È] il difensore della verità, « che si eleva con gli angeli, glorifica con gli arcangeli, fa salire sull'altare del cielo le vittime dei sacrifici, condivide il sacerdozio di Cristo, riplasma la creatura, restaura [in essa] l'immagine [di Dio], la ricrea per il mondo di lassù, e, per dire ciò che vi è di più sublime, è divinizzato e divinizza » E il santo Curato d'Ars: « È il sacerdote che continua l'opera di redenzione sulla terra ». [...] « Se si comprendesse bene il sacerdote qui in terra, si morirebbe non di spavento, ma di amore ». [...] « Il sacerdozio è l'amore del cuore di Gesù » In sintesi</p>
<p>1590 San Paolo dice al suo discepolo Timoteo: « Ti ricordo di ravvivare il dono di Dio che è in te per l'imposizione delle mie mani » (2 Tm 1,6), e: « Se uno aspira all'Episcopato, desidera un nobile lavoro » (1 Tm 3,1). A Tito diceva: « Per questo ti ho lasciato a Creta, perché regolassi ciò che rimane da fare e perché stabilissi presbiteri in ogni città, secondo le istruzioni che ti ho dato » (Tt 1,5).</p>
<p>1591 Tutta la Chiesa è un popolo sacerdotale. Grazie al battesimo, tutti i fedeli partecipano al sacerdozio di Cristo. Tale partecipazione si chiama « sacerdozio comune dei fedeli ». Sulla sua base e al suo servizio esiste un'altra partecipazione alla missione di Cristo: quella del ministero conferito dal sacramento dell'Ordine, la cui funzione è di servire a nome e in persona di Cristo Capo in mezzo alla comunità.</p>
<p>1592 Il sacerdozio ministeriale differisce essenzialmente dal sacerdozio comune dei fedeli poiché conferisce un potere sacro per il servizio dei fedeli. I ministri ordinati esercitano il loro servizio presso il popolo di Dio attraverso l'insegnamento (munus docendi), il culto divino (munus liturgicum) e il governo pastorale (munus regendi).</p>
<p>1593 Fin dalle origini, il ministero ordinato è stato conferito ed esercitato in tre gradi: quello dei Vescovi, quello dei presbiteri e quello dei diaconi. I ministeri conferiti dall'ordinazione sono insostituibili per la struttura organica della Chiesa: senza il Vescovo, i presbiteri e i diaconi, non si può parlare di Chiesa.</p>
<p>1594 Il Vescovo riceve la pienezza del sacramento dell'Ordine che lo inserisce nel Collegio episcopale e fa di lui il capo visibile della Chiesa particolare che gli è affidata. I Vescovi, in quanto successori degli Apostoli e membri del Collegio, hanno parte alla responsabilità apostolica e alla missione di tutta la Chiesa sotto l'autorità del Papa, Successore di san Pietro.</p>
<p>1595 I presbiteri sono uniti ai Vescovi nella dignità sacerdotale e nello stesso tempo dipendono da essi nell'esercizio delle loro funzioni pastorali; sono chiamati ad essere i saggi collaboratori dei Vescovi; riuniti attorno al loro Vescovo formano il « presbiterio », che insieme con lui porta la responsabilità della Chiesa particolare. Essi ricevono dal Vescovo la responsabilità di una comunità parrocchiale o di una determinata funzione ecclesiale.</p>
<p>1596 I diaconi sono ministri ordinati per gli incarichi di servizio della Chiesa; non ricevono il sacerdozio ministeriale, ma l'ordinazione conferisce loro funzioni importanti nel ministero della parola, del culto divino, del governo pastorale e del servizio della carità, compiti che devono assolvere sotto l'autorità pastorale del loro Vescovo.</p>
<p>1597 Il sacramento dell'Ordine è conferito mediante l'imposizione delle mani seguita da una preghiera consacratoria solenne che chiede a Dio per l'ordinando le grazie dello Spirito Santo richieste per il suo ministero. L'ordinazione imprime un carattere sacramentale indelebile.</p>
<p>1598 La Chiesa conferisce il sacramento dell'Ordine soltanto a uomini (viri) battezzati, le cui attitudini per l'esercizio del ministero sono state debitamente riconosciute. Spetta all'autorità della Chiesa la responsabilità e il diritto di chiamare qualcuno a ricevere gli ordini.</p>
<p>1599 Nella Chiesa latina il sacramento dell'Ordine per il presbiterato è conferito normalmente solo a candidati disposti ad abbracciare liberamente il celibato e che manifestano pubblicamente la loro volontà di osservarlo per amore del regno di Dio e del servizio degli uomini.</p>
<p>1600 Spetta ai Vescovi conferire il sacramento dell'Ordine nei tre gradi.</p>
`.trim();
