// Contenuto estratto dal vecchio sito: Il Parroco nel Catechismo della Chiesa Cattolica.
export const PARROCO_CATECHISMO = `
<p>871 « I fedeli sono coloro che, essendo stati incorporati a Cristo mediante il Battesimo, sono costituiti popolo di Dio e perciò, resi partecipi nel modo loro proprio della funzione sacerdotale, profetica e regale di Cristo, sono chiamati ad attuare, secondo la condizione propria di ciascuno, la missione che Dio ha affidato alla Chiesa da compiere nel mondo »</p>
<p>872 « Fra tutti i fedeli, in forza della loro rigenerazione in Cristo, sussiste una vera uguaglianza nella dignità e nell'agire, e per tale uguaglianza tutti cooperano all'edificazione del corpo di Cristo, secondo la condizione e i compiti propri di ciascuno »</p>
<p>873 Le differenze stesse che il Signore ha voluto stabilire fra le membra del suo corpo sono in funzione della sua unità e della sua missione. Infatti « c'è nella Chiesa diversità di ministeri, ma unità di missione. Gli Apostoli e i loro successori hanno avuto da Cristo l'ufficio di insegnare, santificare, reggere in suo nome e con la sua autorità. Ma i laici, resi partecipi dell'ufficio sacerdotale, profetico e regale di Cristo, nella missione di tutto il popolo di Dio assolvono compiti propri nella Chiesa e nel mondo » Infine dai ministri sacri e dai laici « provengono fedeli i quali, con la professione dei consigli evangelici [...], in modo speciale sono consacrati a Dio e danno incremento alla missione salvifica della Chiesa »</p>
<h3>I. La costituzione gerarchica della Chiesa</h3>
<h3>Perché il ministero ecclesiale?</h3>
<p>874 È Cristo stesso l'origine del ministero nella Chiesa. Egli l'ha istituita, le ha dato autorità e missione, orientamento e fine: « Cristo Signore, per pascere e sempre più accrescere il popolo di Dio, ha istituito nella sua Chiesa vari ministeri, che tendono al bene di tutto il corpo. I ministri infatti, che sono dotati di sacra potestà, sono a servizio dei loro fratelli, perché tutti coloro che appartengono al popolo di Dio [...] arrivino alla salvezza »</p>
<p>875 « E come potranno credere, senza averne sentito parlare? E come potranno sentirne parlare senza uno che lo annunzi? E come lo annunzieranno, senza essere prima inviati? » (Rm 10,14-15). Nessuno, né individuo né comunità, può annunziare a se stesso il Vangelo. « La fede dipende [...] dalla predicazione » (Rm 10,17). Nessuno può darsi da sé il mandato e la missione di annunziare il Vangelo. L'inviato del Signore parla e agisce non per autorità propria, ma in forza dell'autorità di Cristo; non come membro della comunità, ma parlando ad essa in nome di Cristo. Nessuno può conferire a se stesso la grazia, essa deve essere data e offerta. Ciò suppone che vi siano ministri della grazia, autorizzati e abilitati da Cristo. Da lui i Vescovi e i presbiteri ricevono la missione e la facoltà (la « sacra potestà ») di agire in persona di Cristo Capo, i diaconi la forza di servire il popolo di Dio nella « diaconia » della liturgia, della parola e della carità, in comunione con il Vescovo e il suo presbiterio. La tradizione della Chiesa chiama « sacramento » questo ministero, attraverso il quale gli inviati di Cristo compiono e danno per dono di Dio quello che da se stessi non possono né compiere né dare. Il ministero della Chiesa viene conferito mediante uno specifico sacramento.</p>
<p>876 Alla natura sacramentale del ministero ecclesiale è intrinsecamente legato il carattere di servizio. I ministri, infatti, in quanto dipendono interamente da Cristo, il quale conferisce missione e autorità, sono veramente « servi di Cristo » (Rm 1,1), ad immagine di lui che ha assunto liberamente per noi « la condizione di servo » (Fil 2,7). Poiché la parola e la grazia di cui sono i ministri non sono loro, ma di Cristo che le ha loro affidate per gli altri, essi si faranno liberamente servi di tutti.396</p>
<p>877 Allo stesso modo, è proprio della natura sacramentale del ministero ecclesiale avere un carattere collegiale. Infatti il Signore Gesù, fin dall'inizio del suo ministero, istituì i Dodici, che « furono ad un tempo il seme del nuovo Israele e l'origine della sacra gerarchia » Scelti insieme, sono anche mandati insieme, e la loro unione fraterna sarà al servizio della comunione fraterna di tutti i fedeli; essa sarà come un riflesso e una testimonianza della comunione delle Persone divine.</p>
<p>398 Per questo ogni Vescovo esercita il suo ministero in seno al Collegio episcopale, in comunione col Vescovo di Roma, Successore di san Pietro e capo del Collegio; i sacerdoti esercitano il loro ministero in seno al presbiterio della diocesi, sotto la direzione del loro Vescovo.</p>
<p>878 Infine è proprio della natura sacramentale del ministero ecclesiale avere un carattere personale. Se i ministri di Cristo agiscono in comunione, agiscono però sempre anche in maniera personale. Ognuno è chiamato personalmente: « Tu seguimi » (Gv 21,22),399 per essere, nella missione comune, testimone personale, personalmente responsabile davanti a colui che conferisce la missione, agendo « in sua persona » e per delle persone: « Io ti battezzo nel nome del Padre... »; « Io ti assolvo... » Pertanto il ministero sacramentale nella Chiesa è un servizio esercitato in nome di Cristo. Esso ha un carattere personale e una forma collegiale. Ciò si verifica sia nei legami tra il Collegio episcopale e il suo capo, il Successore di san Pietro, sia nel rapporto tra la responsabilità pastorale del Vescovo per la sua Chiesa particolare e la sollecitudine di tutto il Collegio episcopale per la Chiesa universale. Il Collegio episcopale e il suo capo, il Papa</p>
<p>880 Cristo istituì i Dodici « sotto la forma di un collegio o di un gruppo stabile, del quale mise a capo Pietro, scelto di mezzo a loro » « Come san Pietro e gli altri Apostoli costituirono, per istituzione del Signore, un unico collegio apostolico, similmente il Romano Pontefice, Successore di Pietro, e i Vescovi, successori degli Apostoli, sono tra loro uniti »</p>
<p>881 Del solo Simone, al quale diede il nome di Pietro, il Signore ha fatto la pietra della sua Chiesa. A lui ne ha affidato le chiavi;402 l'ha costituito pastore di tutto il gregge.</p>
<p>403 « Ma l'incarico di legare e di sciogliere, che è stato dato a Pietro, risulta essere stato pure concesso al collegio degli Apostoli, unito col suo capo » Questo ufficio pastorale di Pietro e degli altri Apostoli costituisce uno dei fondamenti della Chiesa; è continuato dai Vescovi sotto il primato del Papa.</p>
<p>882 Il Papa, Vescovo di Roma e Successore di san Pietro, « è il perpetuo e visibile principio e fondamento dell'unità sia dei Vescovi sia della moltitudine dei fedeli » « Infatti il Romano Pontefice, in virtù del suo ufficio di Vicario di Cristo e di Pastore di tutta la Chiesa, ha sulla Chiesa la potestà piena, suprema e universale, che può sempre esercitare liberamente »</p>
<p>883 « Il Collegio o Corpo dei Vescovi non ha autorità, se non lo si concepisce insieme con il Romano Pontefice, [...] quale suo capo ». Come tale, questo Collegio « è pure soggetto di suprema e piena potestà su tutta la Chiesa: potestà che non può essere esercitata se non con il consenso del Romano Pontefice »</p>
<p>884 « Il Collegio dei Vescovi esercita in modo solenne la potestà sulla Chiesa universale nel Concilio Ecumenico » « Mai si ha Concilio Ecumenico, che come tale non sia confermato o almeno accettato dal Successore di Pietro »</p>
<p>885 « Il Collegio episcopale, in quanto composto da molti, esprime la varietà e l'universalità del popolo di Dio; in quanto raccolto sotto un solo capo, esprime l'unità del gregge di Cristo »</p>
<p>886 « I Vescovi, singolarmente presi, sono il principio visibile e il fondamento dell'unità nelle loro Chiese particolari » In quanto tali « esercitano il loro pastorale governo sopra la porzione del popolo di Dio che è stata loro affidata »,412 coadiuvati dai presbiteri e dai diaconi. Ma, in quanto membri del Collegio episcopale, ognuno di loro è partecipe della sollecitudine per tutte le Chiese,413 e la esercita innanzi tutto «reggendo bene la propria Chiesa come porzione della Chiesa universale», contribuendo così «al bene di tutto il corpo mistico che è pure il corpo delle Chiese» Tale sollecitudine si estenderà particolarmente ai poveri,415 ai perseguitati per la fede, come anche ai missionari che operano in tutta la terra.</p>
<p>887 Le Chiese particolari vicine e di cultura omogenea formano province ecclesiastiche o realtà più vaste chiamate patriarcati o regioni.</p>
<p>416 I Vescovi di questi raggruppamenti possono riunirsi in Sinodi o in Concilii provinciali. « Così pure, le Conferenze Episcopali possono, oggi, contribuire in modo molteplice e fecondo a che lo spirito collegiale si attui concretamente » L'ufficio di insegnare</p>
<p>888 I Vescovi, con i presbiteri, loro cooperatori, « hanno anzitutto il dovere di annunziare a tutti il Vangelo di Dio »,418 secondo il comando del Signore.</p>
<p>419 Essi sono « gli araldi della fede, che portano a Cristo nuovi discepoli, sono i dottori autentici » della fede apostolica, « rivestiti dell'autorità di Cristo »</p>
<p>889 Per mantenere la Chiesa nella purezza della fede trasmessa dagli Apostoli, Cristo, che è la verità, ha voluto rendere la sua Chiesa partecipe della propria infallibilità. Mediante il « senso soprannaturale della fede », il popolo di Dio « aderisce indefettibilmente alla fede », sotto la guida del Magistero vivente della Chiesa.421</p>
<p>890 La missione del Magistero è legata al carattere definitivo dell'Alleanza che Dio in Cristo ha stretto con il suo popolo; deve salvaguardarlo dalle deviazioni e dai cedimenti, e garantirgli la possibilità oggettiva di professare senza errore l'autentica fede. Il compito pastorale del Magistero è quindi ordinato a vigilare affinché il popolo di Dio rimanga nella verità che libera. Per compiere questo servizio, Cristo ha dotato i Pastori del carisma dell'infallibilità in materia di fede e di costumi. L'esercizio di questo carisma può avere parecchie modalità.</p>
<p>891 « Di questa infallibilità il Romano Pontefice, capo del Collegio dei Vescovi, fruisce in virtù del suo ufficio, quando, quale supremo Pastore e Dottore di tutti i fedeli, che conferma nella fede i suoi fratelli, proclama con un atto definitivo una dottrina riguardante la fede o la morale. [...] L'infallibilità promessa alla Chiesa risiede pure nel Corpo episcopale, quando questi esercita il supremo Magistero col Successore di Pietro » soprattutto in un Concilio Ecumenico.</p>
<p>422 Quando la Chiesa, mediante il suo Magistero supremo, propone qualche cosa « da credere come rivelato da Dio » e come insegnamento di Cristo, « a tali definizioni si deve aderire con l'ossequio della fede » Tale infallibilità abbraccia l'intero deposito della rivelazione divina.425</p>
<p>892 L'assistenza divina è inoltre data ai successori degli Apostoli, che insegnano in comunione con il Successore di Pietro, e, in modo speciale, al Vescovo di Roma, Pastore di tutta la Chiesa, quando, pur senza arrivare ad una definizione infallibile e senza pronunciarsi in « maniera definitiva », propongono, nell'esercizio del Magistero ordinario, un insegnamento che porta ad una migliore intelligenza della Rivelazione in materia di fede e di costumi. A questo insegnamento ordinario i fedeli devono « aderire col religioso ossequio dello spirito » che, pur distinguendosi dall'ossequio della fede, tuttavia ne è il prolungamento. L'ufficio di santificare</p>
<p>893 Il Vescovo « è il dispensatore della grazia del supremo sacerdozio »,427 specialmente nell'Eucaristia che egli stesso offre o di cui assicura l'offerta mediante i presbiteri, suoi cooperatori. L'Eucaristia, infatti, è il centro della vita della Chiesa particolare. Il Vescovo e i presbiteri santificano la Chiesa con la loro preghiera e il loro lavoro, con il ministero della parola e dei sacramenti. La santificano con il loro esempio, « non spadroneggiando sulle persone » loro « affidate », ma facendosi « modelli del gregge » (1 Pt 5,3), in modo che « possano, insieme col gregge loro affidato, giungere alla vita eterna » L'ufficio di governare</p>
<p>894 « I Vescovi reggono le Chiese particolari, come vicari e delegati di Cristo, col consiglio, la persuasione, l'esempio, ma anche con l'autorità e la sacra potestà »,429 che però dev'essere da loro esercitata allo scopo di edificare, nello spirito di servizio che è proprio del loro Maestro.430</p>
<p>895 « Questa potestà, che personalmente esercitano in nome di Cristo, è propria, ordinaria e immediata, quantunque il suo esercizio sia in definitiva regolato dalla suprema autorità della Chiesa» Ma i Vescovi non devono essere considerati come dei vicari del Papa, la cui autorità ordinaria e immediata su tutta la Chiesa non annulla quella dei Vescovi, ma anzi la conferma e la difende. Tale autorità deve esercitarsi in comunione con tutta la Chiesa sotto la guida del Papa.</p>
<p>896 Il Buon Pastore sarà il modello e la « forma » dell'ufficio pastorale del Vescovo. Cosciente delle proprie debolezze, « il Vescovo può compatire quelli che sono nell'ignoranza o nell'errore. Non rifugga dall'ascoltare i sudditi che cura come veri figli suoi. [...] I fedeli poi devono aderire al Vescovo come la Chiesa a Gesù Cristo e come Gesù Cristo al Padre »:</p>
<p>432 « Obbedite tutti al Vescovo, come Gesù Cristo al Padre, e al presbiterio come agli Apostoli; quanto ai diaconi, rispettateli come la Legge di Dio. Nessuno compia qualche azione riguardante la Chiesa, senza il Vescovo » II. I fedeli laici</p>
<p>897 « Col nome di laici si intendono qui tutti i fedeli a esclusione dei membri dell'ordine sacro e dello stato religioso riconosciuto dalla Chiesa, i fedeli cioè, che, dopo essere stati incorporati a Cristo col Battesimo e costituiti popolo di Dio, e nella loro misura resi partecipi della funzione sacerdotale, profetica e regale di Cristo, per la loro parte compiono, nella Chiesa e nel mondo, la missione propria di tutto il popolo cristiano » La vocazione dei laici</p>
<p>898 « Per loro vocazione è proprio dei laici cercare il regno di Dio trattando le cose temporali e ordinandole secondo Dio. [...] A loro quindi particolarmente spetta illuminare e ordinare tutte le realtà temporali, alle quali essi sono strettamente legati, in modo che sempre siano fatte secondo Cristo, e crescano e siano di lode al Creatore e al Redentore »</p>
<p>899 L'iniziativa dei cristiani laici è particolarmente necessaria quando si tratta di scoprire, di ideare mezzi per permeare delle esigenze della dottrina e della vita cristiana le realtà sociali, politiche ed economiche. Questa iniziativa è un elemento normale della vita della Chiesa: « I fedeli laici si trovano sulla linea più avanzata della vita della Chiesa; grazie a loro, la Chiesa è il principio vitale della società. Per questo essi soprattutto devono avere una coscienza sempre più chiara non soltanto di appartenere alla Chiesa, ma di essere la Chiesa, cioè la comunità dei fedeli sulla terra sotto la guida dell'unico capo, il Papa, e dei Vescovi in comunione con lui. Essi sono la Chiesa »</p>
<p>900 I laici, come tutti i fedeli, in virtù del Battesimo e della Confermazione, ricevono da Dio l'incarico dell'apostolato; pertanto hanno l'obbligo e godono del diritto, individualmente o riuniti in associazioni, di impegnarsi affinché il messaggio divino della salvezza sia conosciuto e accolto da tutti gli uomini e su tutta la terra; tale obbligo è ancora più pressante nei casi in cui solo per mezzo loro gli uomini possono ascoltare il Vangelo e conoscere Cristo. Nelle comunità ecclesiali, la loro azione è così necessaria che, senza di essa, l'apostolato dei Pastori, la maggior parte delle volte, non può raggiungere il suo pieno effetto.</p>
<p>437 La partecipazione dei laici all'ufficio sacerdotale di Cristo</p>
<p>901 « I laici, essendo dedicati a Cristo e consacrati dallo Spirito Santo, sono in modo mirabile chiamati e istruiti perché lo Spirito produca in essi frutti sempre più copiosi. Tutte infatti le opere, le preghiere e le iniziative apostoliche, la vita coniugale e familiare, il lavoro giornaliero, il sollievo spirituale e corporale, se sono compiute nello Spirito, e persino le molestie della vita, se sono sopportate con pazienza, diventano sacrifici spirituali graditi a Dio per mezzo di Gesù Cristo;438 e queste cose nella celebrazione dell'Eucaristia sono piissimamente offerte al Padre insieme all'oblazione del Corpo del Signore. Così anche i laici, operando santamente dappertutto come adoratori, consacrano a Dio il mondo stesso »</p>
<p>902 In modo particolare i genitori partecipano all'ufficio di santificazione « conducendo la vita coniugale secondo lo spirito cristiano e attendendo all'educazione cristiana dei figli »</p>
<p>903 I laici, se hanno le doti richieste, possono essere assunti stabilmente ai ministeri di lettori e di accoliti.</p>
<p>441 « Ove lo suggerisca la necessità della Chiesa, in mancanza di ministri, anche i laici, pur senza essere lettori o accoliti, possono supplire alcuni dei loro uffici, cioè esercitare il ministero della parola, presiedere alle preghiere liturgiche, amministrare il Battesimo e distribuire la sacra Comunione, secondo le disposizioni del diritto » La loro partecipazione all'ufficio profetico di Cristo</p>
<p>904 « Cristo [...] adempie la sua funzione profetica... non solo per mezzo della gerarchia, [...] ma anche per mezzo dei laici, che perciò costituisce suoi testimoni e forma nel senso della fede e nella grazia della parola »:</p>
<p>443 «Istruire qualcuno per condurlo alla fede è il compito di ogni predicatore e anche di ogni credente»</p>
<p>905 I laici compiono la loro missione profetica anche mediante l'evangelizzazione, cioè « con l'annunzio di Cristo fatto con la testimonianza della vita e con la parola ». Questa azione evangelizzatrice ad opera dei laici « acquista una certa nota specifica e una particolare efficacia dal fatto che viene compiuta nelle comuni condizioni del secolo»:</p>
<p>445 « Tale apostolato non consiste nella sola testimonianza della vita: il vero apostolo cerca le occasioni per annunziare Cristo con la parola, sia ai credenti [...], sia agli infedeli »</p>
<p>906 Tra i fedeli laici coloro che ne sono capaci e che vi si preparano possono anche prestare la loro collaborazione alla formazione catechistica,447 all'insegnamento delle scienze sacre,448 ai mezzi di comunicazione sociale.449</p>
<p>907 « In rapporto alla scienza, alla competenza e al prestigio di cui godono, essi hanno il diritto, e anzi talvolta anche il dovere, di manifestare ai sacri Pastori il loro pensiero su ciò che riguarda il bene della Chiesa e di renderlo noto agli altri fedeli, salva restando l'integrità della fede e dei costumi e il rispetto verso i Pastori, tenendo inoltre presente l'utilità comune e la dignità della persona » La loro partecipazione all'ufficio regale di Cristo</p>
<p>908 Mediante la sua obbedienza fino alla morte,</p>
<p>451 Cristo ha comunicato ai suoi discepoli il dono della libertà regale, « perché con l'abnegazione di sé e la vita santa vincano in se stessi il regno del peccato » « Colui che sottomette il proprio corpo e governa la sua anima senza lasciarsi sommergere dalle passioni è padrone di sé: può essere chiamato re perché è capace di governare la propria persona; è libero e indipendente e non si lascia imprigionare da una colpevole schiavitù »</p>
<p>909 « Inoltre i laici, anche mettendo in comune la loro forza, risanino le istituzioni e le condizioni di vita del mondo, se ve ne sono che spingano i costumi al peccato, così che tutte siano rese conformi alle norme della giustizia e, anziché ostacolare, favoriscano l'esercizio delle virtù. Così agendo impregneranno di valore morale la cultura e i lavori dell'uomo »</p>
<p>910 « I laici [...] possono anche sentirsi chiamati o essere chiamati a collaborare con i loro Pastori nel servizio della comunità ecclesiale, per la crescita e la vitalità della medesima, esercitando ministeri diversissimi, secondo la grazia e i carismi che il Signore vorrà loro dispensare »</p>
<p>911 Nella Chiesa, nell'esercizio della medesima potestà di governo, « i fedeli laici possono cooperare a norma del diritto » E questo mediante la loro presenza nei Concili particolari,457 nei Sinodi diocesani,458 nei Consigli pastorali;459 nell'esercizio della cura pastorale di una parrocchia;460 nella collaborazione ai Consigli degli affari economici;461 nella partecipazione ai tribunali ecclesiastici,462 ecc.</p>
<p>912 I fedeli devono « distinguere accuratamente tra i diritti e i doveri che loro incombono in quanto sono aggregati alla Chiesa, e quelli che loro competono in quanto membri della società umana. Cerchino di metterli in armonia, ricordandosi che in ogni cosa temporale devono essere guidati dalla coscienza cristiana, poiché nessuna attività umana, neanche in materia temporale, può essere sottratta al dominio di Dio »</p>
<p>913 « Così ogni laico, in ragione degli stessi doni ricevuti, è un testimone e insieme uno strumento vivo della missione della Chiesa stessa "secondo la misura del dono di Cristo" (Ef 4,7) » III. La vita consacrata</p>
<p>914 « Lo stato [di vita] che è costituito dalla professione dei consigli evangelici, pur non appartenendo alla struttura gerarchica della Chiesa, interessa tuttavia indiscutibilmente la sua vita e la sua santità » Consigli evangelici, vita consacrata</p>
<p>915 I consigli evangelici, nella loro molteplicità, sono proposti ad ogni discepolo di Cristo. La perfezione della carità, alla quale tutti i fedeli sono chiamati, comporta per coloro che liberamente accolgono la vocazione alla vita consacrata l'obbligo di praticare la castità nel celibato per il Regno, la povertà e l'obbedienza. È la professione di tali consigli, in uno stato di vita stabile riconosciuto dalla Chiesa, che caratterizza la « vita consacrata » a Dio.</p>
<p>916 Lo stato di vita consacrata appare quindi come uno dei modi di conoscere una consacrazione « più intima », che si radica nel Battesimo e si dedica totalmente a Dio.</p>
<p>467 Nella vita consacrata, i fedeli di Cristo si propongono, sotto la mozione dello Spirito Santo, di seguire Cristo più da vicino, di donarsi a Dio amato sopra ogni cosa e, tendendo alla perfezione della carità a servizio del Regno, di significare e annunziare nella Chiesa la gloria del mondo futuro.</p>
<p>468 Un grande albero dai molti rami</p>
<p>917 « Come in un albero piantato da Dio e in un modo mirabile e molteplice ramificatosi nel campo del Signore, sono cresciute varie forme di vita solitaria o comune e varie Famiglie, che si sviluppano sia per il profitto dei loro membri, sia per il bene di tutto il corpo di Cristo »</p>
<p>918 « Fin dai primi tempi della Chiesa vi furono uomini e donne che per mezzo della pratica dei consigli evangelici intesero seguire Cristo con maggiore libertà e imitarlo più da vicino e condussero, ciascuno a loro modo, una vita consacrata a Dio. Molti di essi, dietro l'impulso dello Spirito Santo, o vissero una vita solitaria o fondarono Famiglie religiose, che la Chiesa con la sua autorità volentieri accolse e approvò »</p>
<p>919 I Vescovi si premureranno sempre di discernere i nuovi doni della vita consacrata affidati dallo Spirito Santo alla sua Chiesa; l'approvazione di nuove forme di vita consacrata è riservata alla Sede Apostolica.</p>
<p>471 La vita eremitica</p>
<p>920 Senza professare sempre pubblicamente i tre consigli evangelici, gli eremiti, « in una più rigorosa separazione dal mondo, nel silenzio della solitudine e nell'assidua preghiera e nella penitenza, dedicano la propria vita alla lode di Dio e alla salvezza del mondo »</p>
<p>921 Essi indicano a ogni uomo quell'aspetto interiore del mistero della Chiesa che è l'intimità personale con Cristo. Nascosta agli occhi degli uomini, la vita dell'eremita è predicazione silenziosa di colui al quale ha consegnato la sua vita, poiché egli è tutto per lui. È una chiamata particolare a trovare nel deserto, proprio nel combattimento spirituale, la gloria del Crocifisso. Le vergini e le vedove consacrate</p>
<p>922 Fin dai tempi apostolici, ci furono vergini 473 e vedove 474 cristiane che, chiamate dal Signore a dedicarsi esclusivamente a lui in una maggiore libertà di cuore, di corpo e di spirito, hanno preso la decisione, approvata dalla Chiesa, di vivere nello stato rispettivamente di verginità o di castità perpetua « per il regno dei cieli » (Mt 19,12).</p>
<p>923 « Emettendo il santo proposito di seguire Cristo più da vicino, [le vergini] dal Vescovo diocesano sono consacrate a Dio secondo il rito liturgico approvato e, unite in mistiche nozze a Cristo Figlio di Dio, si dedicano al servizio della Chiesa » Mediante questo rito solenne (Consecratio virginum), « la vergine è costituita persona consacrata » quale « segno trascendente dell'amore della Chiesa verso Cristo, immagine escatologica della Sposa celeste e della vita futura»</p>
<p>924 Aggiungendosi alle altre forme di vita consacrata, 477 l'ordine delle vergini stabilisce la donna che vive nel mondo (o la monaca) nella preghiera, nella penitenza, nel servizio dei fratelli e nel lavoro apostolico, secondo lo stato e i rispettivi carismi offerti ad ognuna.</p>
<p>478 Le vergini consacrate possono associarsi al fine di mantenere più fedelmente il loro proposito.</p>
<p>479 La vita religiosa</p>
<p>925 Nata in Oriente nei primi secoli del cristianesimo 480 e continuata negli istituti canonicamente eretti dalla Chiesa, 481 la vita religiosa si distingue dalle altre forme di vita consacrata per l'aspetto cultuale, la professione pubblica dei consigli evangelici, la vita fraterna condotta in comune, la testimonianza resa all'unione di Cristo e della Chiesa.</p>
<p>926 La vita religiosa sgorga dal mistero della Chiesa. È un dono che la Chiesa riceve dal suo Signore e che essa offre come uno stato di vita stabile al fedele chiamato da Dio nella professione dei consigli. Così la Chiesa può manifestare Cristo e insieme riconoscersi Sposa del Salvatore. Alla vita religiosa, nelle sue molteplici forme, è chiesto di esprimere la carità stessa di Dio, nel linguaggio del nostro tempo.</p>
<p>927 Tutti i religiosi, esenti o non esenti, 483 sono annoverati fra i cooperatori del Vescovo diocesano nel suo ufficio pastorale.</p>
<p>484 La fondazione e l'espansione missionaria della Chiesa richiedono la presenza della vita religiosa in tutte le sue forme fin dagli inizi dell'evangelizzazione.</p>
<p>485 « La storia attesta i grandi meriti delle Famiglie religiose nella propagazione della fede e nella formazione di nuove Chiese, dalle antiche istituzioni monastiche e dagli Ordini medievali fino alle moderne Congregazioni » Gli istituti secolari</p>
<p>928 « L'istituto secolare è un istituto di vita consacrata in cui i fedeli, vivendo nel mondo, tendono alla perfezione della carità e si impegnano per la santificazione del mondo, soprattutto operando all'interno di esso »</p>
<p>929 Mediante una « vita perfettamente e interamente consacrata a [tale] santificazione », 488 i membri di questi istituti « partecipano della funzione evangelizzatrice della Chiesa », « nel mondo e dal mondo », 489 in cui la loro presenza agisce come un fermento.</p>
<p>490 La loro testimonianza di vita cristiana mira a ordinare secondo Dio le realtà temporali e a vivificare il mondo con la forza del Vangelo. Essi assumono con vincoli sacri i consigli evangelici e custodiscono tra loro la comunione e la fraternità che sono proprie al loro modo di vita secolare.</p>
<p>491 Le società di vita apostolica</p>
<p>930 Alle diverse forme di vita consacrata « si aggiungono le società di vita apostolica i cui membri, senza voti religiosi, perseguono il fine apostolico proprio della società e, conducendo vita fraterna in comunità secondo un proprio stile, tendono alla perfezione della carità mediante l'osservanza delle costituzioni. Fra queste vi sono società i cui membri assumono i consigli evangelici », secondo le loro costituzioni.</p>
<p>492 Consacrazione e missione: annunziare il Re che viene</p>
<p>931 Consegnato a Dio sommamente amato, colui che già era stato votato a lui dal Battesimo, si trova in tal modo più intimamente consacrato al servizio divino e dedito al bene della Chiesa. Con lo stato di consacrazione a Dio, la Chiesa manifesta Cristo e mostra come lo Spirito Santo agisca in essa in modo mirabile. Coloro che professano i consigli evangelici hanno, dunque, come prima missione, quella di vivere la loro consacrazione. Ma « dal momento che in forza della stessa consacrazione si dedicano al servizio della Chiesa, sono tenuti all'obbligo di prestare l'opera loro in modo speciale nell'azione missionaria, con lo stile proprio dell'Istituto »</p>
<p>932 Nella Chiesa che è come il sacramento, cioè il segno e lo strumento della vita di Dio, la vita consacrata appare come un segno particolare del mistero della redenzione. Seguire e imitare Cristo « più da vicino », manifestare « più chiaramente » il suo annientamento, significa trovarsi « più profondamente » presenti, nel cuore di Cristo, ai propri contemporanei. Coloro, infatti, che camminano in questa via « più stretta » stimolano con il proprio esempio i loro fratelli e «testimoniano in modo splendido che il mondo non può essere trasfigurato e offerto a Dio senza lo spirito delle beatitudini»</p>
<p>933 Che tale testimonianza sia pubblica, come nello stato religioso, oppure più discreta, o addirittura segreta, la venuta di Cristo rimane per tutti i consacrati l'origine e l'orientamento della loro vita: « Poiché il popolo di Dio non ha qui città permanente, [...] (lo stato religioso) rende visibile per tutti i credenti la presenza, già in questo mondo, dei beni celesti; meglio testimonia la vita nuova ed eterna acquistata dalla redenzione di Cristo, e meglio preannunzia la futura risurrezione e la gloria del regno celeste » In sintesi</p>
<p>934 « Per istituzione divina vi sono nella Chiesa tra i fedeli i ministri sacri, che nel diritto sono chiamati anche chierici; gli altri poi sono chiamati anche laici ». Dagli uni e dagli altri provengono fedeli, i quali, con la professione dei consigli evangelici, sono consacrati a Dio e così danno incremento alla missione della Chiesa.</p>
<p>935 Per annunziare la fede e instaurare il suo regno, Cristo invia i suoi Apostoli e i loro successori. Li rende partecipi della sua missione. Da lui ricevono il potere di agire in sua persona.</p>
<p>936 Il Signore ha fatto di san Pietro il fondamento visibile della sua Chiesa. A lui ne ha affidato le chiavi. Il Vescovo della Chiesa di Roma, Successore di san Pietro, è « Capo del Collegio dei Vescovi, Vicario di Cristo e Pastore qui in terra della Chiesa universale »</p>
<p>937 Il Papa « è per divina istituzione rivestito di un potere supremo, pieno, immediato e universale per il bene delle anime »</p>
<p>938 I Vescovi, costituiti per mezzo dello Spirito Santo, succedono agli Apostoli. «Singolarmente presi, sono il principio visibile e il fondamento dell'unità nelle loro Chiese particolari»</p>
<p>939 Aiutati dai presbiteri, loro cooperatori, e dai diaconi, i Vescovi hanno l'ufficio di insegnare autenticamente la fede, di celebrare il culto divino, soprattutto l'Eucaristia, e di guidare la loro Chiesa da veri Pastori. È inerente al loro ufficio anche la sollecitudine per tutte le Chiese, con il Papa e sotto di lui.</p>
<p>940 « I laici, essendo proprio del loro stato che vivano nel mondo e in mezzo agli affari secolari, sono chiamati da Dio affinché, ripieni di spirito cristiano, a modo di fermento esercitino nel mondo il loro apostolato »</p>
<p>941 I laici partecipano al sacerdozio di Cristo: sempre più uniti a lui, dispiegano la grazia del Battesimo e della Confermazione in tutte le dimensioni della vita personale, familiare, sociale ed ecclesiale, e realizzano così la chiamata alla santità rivolta a tutti i battezzati.</p>
<p>942 Grazie alla loro missione profetica, « i laici sono chiamati anche ad essere testimoni di Cristo in mezzo a tutti, e cioè pure in mezzo alla società umana »</p>
<p>943 Grazie alla loro missione regale, i laici hanno il potere di vincere in se stessi e nel mondo il regno del peccato con l'abnegazione di sé e la santità della loro vita.</p>
<p>944 La vita consacrata a Dio si caratterizza mediante la professione pubblica dei consigli evangelici di povertà, castità e obbedienza in uno stato di vita stabile riconosciuto dalla Chiesa.</p>
<p>945 Consegnato a Dio sommamente amato, colui che era già stato destinato a lui dal Battesimo si trova, nello stato di vita consacrata, più intimamente votato al servizio divino e dedito al bene di tutta la Chiesa.</p>
`.trim();
