// Contenuto: Il Parroco nel Codice di Diritto Canonico (cann. 515-552).
export const PARROCO_CODICE_CANONICO = `
<p class="intro">LIBRO II<br>IL POPOLO DI DIO<br>PARTE II<br>LA COSTITUZIONE GERARCHICA DELLA CHIESA<br>SEZIONE II<br>LE CHIESE PARTICOLARI E I LORO RAGGRUPPAMENTI<br>(CANN. 368 – 572)<br>TITOLO III<br>STRUTTURA INTERNA DELLE CHIESE PARTICOLARI<br>(CANN. 460 – 572)<br>CAPITOLO VI (CANN. 515 - 552)<br>LE PARROCCHIE, I PARROCI E I VICARI PARROCCHIALI</p>
<p><strong>Can. 515</strong> - §1. La parrocchia è una determinata comunità di fedeli che viene costituita stabilmente nell'àmbito di una Chiesa particolare, la cui cura pastorale è affidata, sotto l'autorità del Vescovo diocesano, ad un parroco quale suo proprio pastore.</p>
<p>§2. Spetta unicamente al Vescovo diocesano erigere, sopprimere o modificare le parrocchie; egli non le eriga, non le sopprima e non le modifichi in modo rilevante senza aver sentito il consiglio presbiterale.</p>
<p>§3. La parrocchia eretta legittimamente gode di personalità giuridica per il diritto stesso.</p>
<p><strong>Can. 516</strong> - §1. A meno che il diritto non disponga diversamente, alla parrocchia è equiparata la quasi-parrocchia, che è una comunità determinata di fedeli nell'àmbito della Chiesa particolare, affidata ad un sacerdote come suo pastore, che, per speciali circostanze, non è ancora stata eretta come parrocchia.</p>
<p>§2. Quando una comunità non può essere eretta come parrocchia o quasi-parrocchia, il Vescovo diocesano provveda in altro modo alla sua cura pastorale.</p>
<p><strong>Can. 517</strong> - §1. Quando le circostanze lo richiedono, la cura pastorale di una parrocchia, o di più parrocchie contemporaneamente, può essere affidata in solido a più sacerdoti, a condizione tuttavia che uno di essi ne sia il moderatore nell'esercizio della cura pastorale, tale cioè che diriga l'attività comune e di essa risponda davanti al Vescovo.</p>
<p>§2. Nel caso che il Vescovo diocesano, a motivo della scarsità di sacerdoti, abbia giudicato di dover affidare ad un diacono o ad una persona non insignita del carattere sacerdotale o ad una comunità di persone una partecipazione nell'esercizio della cura pastorale di una parrocchia, costituisca un sacerdote il quale, con la potestà e le facoltà di parroco, sia il moderatore della cura pastorale.</p>
<p><strong>Can. 518</strong> - Come regola generale, la parrocchia sia territoriale, tale cioè che comprenda tutti i fedeli di un determinato territorio; dove però risulti opportuno, vengano costituite parrocchie personali, sulla base del rito, della lingua, della nazionalità dei fedeli di un territorio, oppure anche sulla base di altri criteri.</p>
<p><strong>Can. 519</strong> - Il parroco è il pastore proprio della parrocchia affidatagli, esercitando la cura pastorale di quella comunità sotto l'autorità del Vescovo diocesano, con il quale è chiamato a partecipare al ministero di Cristo, per compiere al servizio della comunità le funzioni di insegnare, santificare e governare, anche con la collaborazione di altri presbiteri o diaconi e con l'apporto dei fedeli laici, a norma del diritto.</p>
<p><strong>Can. 520</strong> - §1. Il parroco non sia una persona giuridica; tuttavia il Vescovo diocesano, ma non l'Amministratore diocesano, con il consenso del Superiore competente, può affidare una parrocchia ad un istituto religioso clericale o ad una società clericale di vita apostolica, anche erigendola presso la chiesa dell'istituto o della società, a condizione però che un solo presbitero sia il parroco della parrocchia, oppure, se la cura pastorale è affidata in solido a più presbiteri, il moderatore di cui nel can. 517, §1.</p>
<p>§2. L'assegnazione della parrocchia di cui al §1 può essere fatta sia in perpetuo, sia a tempo determinato; in ambedue i casi avvenga mediante una convenzione scritta stipulata fra il Vescovo diocesano e il Superiore competente dell'istituto o della società; in essa, fra l'altro, venga definito espressamente e con precisione tutto quello che riguarda l'attività da svolgere, le persone da impiegarvi e gli aspetti economici.</p>
<p><strong>Can. 521</strong> - §1. Perché uno sia nominato parroco validamente, deve essere costituito nel sacro ordine del presbiterato.</p>
<p>§2. Si distingua inoltre per sana dottrina e onestà di costumi, sia dotato di zelo per le anime e di ogni altra virtù e abbia quelle qualità che sono richieste sia dal diritto universale, sia dal diritto particolare per la cura pastorale della parrocchia in questione.</p>
<p>§3. Per conferire a qualcuno l'ufficio di parroco, è opportuno che venga accertata con sicurezza la sua idoneità nel modo determinato dal Vescovo, anche mediante un esame.</p>
<p><strong>Can. 522</strong> - È necessario che il parroco goda di stabilità, perciò venga nominato a tempo indeterminato; il Vescovo diocesano può nominarlo a tempo determinato solamente se ciò fu ammesso per decreto dalla Conferenza Episcopale.</p>
<p><strong>Can. 523</strong> - Fermo restando il disposto del can. 682, §1, la provvisione dell'ufficio di parroco spetta al Vescovo diocesano; essa avviene mediante libero conferimento, a meno che qualcuno non abbia il diritto di presentazione o di elezione.</p>
<p><strong>Can. 524</strong> - Il Vescovo diocesano, dopo aver valutato tutte le circostanze, affidi la parrocchia vacante a chi ritiene idoneo ad esercitarvi la cura pastorale, esclusa ogni preferenza di persone; per giudicarne l'idoneità, senta il vicario foraneo ed esegua le indagini opportune, uditi, se del caso, determinati presbiteri come pure fedeli laici.</p>
<p><strong>Can. 525</strong> - Mentre la sede è vacante o impedita, all'Amministratore diocesano o a colui che regge interinalmente la diocesi spetta:</p>
<p>1) concedere l'istituzione o la conferma ai presbiteri legittimamente presentati o eletti per una parrocchia;</p>
<p>2) nominare i parroci se la sede è vacante o impedita da un anno.</p>
<p><strong>Can. 526</strong> - §1. Il parroco abbia la cura pastorale di una sola parrocchia; tuttavia, per la scarsità di sacerdoti o per altre circostanze, può essere affidata al medesimo parroco la cura di più parrocchie vicine.</p>
<p>§2. Nella medesima parrocchia vi sia soltanto un parroco o un moderatore a norma del can. 517, §1, riprovata ogni consuetudine contraria e revocato ogni privilegio contrario.</p>
<p><strong>Can. 527</strong> - §1. Colui che è stato promosso alla cura pastorale di una parrocchia, la ottiene ed è tenuto ad esercitarla dal momento della presa di possesso.</p>
<p>§2. L'immissione in possesso del parroco spetta all'Ordinario del luogo o ad un sacerdote da lui delegato e devono essere osservate le modalità determinate dalla legge particolare o dalla legittima consuetudine; tuttavia, per giusta causa, il medesimo Ordinario può dispensare da tali modalità; in tal caso la dispensa notificata alla parrocchia sostituisce la presa di possesso.</p>
<p>§3. L'Ordinario del luogo determini il tempo entro il quale deve avvenire la presa di possesso della parrocchia; trascorso inutilmente tale tempo, se non si sia opposto un giusto impedimento, può dichiarare la parrocchia vacante.</p>
<p><strong>Can. 528</strong> - §1. Il parroco è tenuto a fare in modo che la parola di Dio sia integralmente annunciata a coloro che si trovano nella parrocchia; perciò curi che i fedeli laici siano istruiti nelle verità della fede, soprattutto con l'omelia da tenere nelle domeniche e nelle feste di precetto e con l'istruzione catechistica da impartire; favorisca inoltre le attività che promuovono lo spirito evangelico, anche in ordine alla giustizia sociale; abbia cura speciale della formazione cattolica dei fanciulli e dei giovani; si impegni in ogni modo, anche con la collaborazione dei fedeli, perché l'annuncio evangelico giunga anche a coloro che si sono allontanati dalla pratica religiosa o non professano la vera fede.</p>
<p>§2. Il parroco faccia in modo che la santissima Eucaristia sia il centro dell'assemblea parrocchiale dei fedeli; si adoperi perché i fedeli si nutrano mediante la celebrazione devota dei sacramenti e in special modo perché si accostino frequentemente al sacramento della santissima Eucaristia e della penitenza; si impegni inoltre a fare in modo che i fedeli siano formati alla preghiera, da praticare anche nella famiglia, e partecipino consapevolmente e attivamente alla sacra liturgia, di cui il parroco deve essere il moderatore nella sua parrocchia, sotto l'autorità del Vescovo diocesano e sulla quale è tenuto a vigilare perché non si insinuino abusi.</p>
<p><strong>Can. 529</strong> - §1. Per adempiere diligentemente l'ufficio di pastore, il parroco cerchi di conoscere i fedeli affidati alle sue cure; perciò visiti le famiglie, partecipando alle sollecitudini dei fedeli, soprattutto alle loro angosce e ai loro lutti, confortandoli nel Signore e, se hanno mancato in qualche cosa, correggendoli con prudenza; assista con traboccante carità gli ammalati, soprattutto quelli vicini alla morte, nutrendoli con sollecitudine dei sacramenti e raccomandandone l'anima a Dio; con speciale diligenza sia vicino ai poveri e agli ammalati, agli afflitti, a coloro che sono soli, agli esuli e a tutti coloro che attraversano particolari difficoltà; si impegni anche perché gli sposi e i genitori siano sostenuti nell'adempimento dei loro doveri e favorisca l'incremento della vita cristiana nella famiglia.</p>
<p>§2. Il parroco riconosca e promuova il ruolo che hanno i fedeli laici nella missione della Chiesa, favorendo le loro associazioni che si propongono finalità religiose. Collabori con il proprio Vescovo e con il presbiterio della diocesi, impegnandosi anche perché i fedeli si prendano cura di favorire la comunione parrocchiale, perché si sentano membri e della diocesi e della Chiesa universale e perché partecipino e sostengano le opere finalizzate a promuovere la comunione.</p>
<p><strong>Can. 530</strong> - Le funzioni affidate al parroco in modo speciale sono le seguenti:</p>
<p>1) amministrare il battesimo;</p>
<p>2) amministrare il sacramento della confermazione a coloro che sono in pericolo di morte, a norma del can. 883, n. 3;</p>
<p>3) amministrare il Viatico e l'unzione degli infermi, fermo restando il disposto del can. 1003, §§2 e 3, e impartire la benedizione apostolica;</p>
<p>4) assistere al matrimonio e benedire le nozze;</p>
<p>5) celebrare i funerali;</p>
<p>6) benedire il fonte battesimale nel tempo pasquale, guidare le processioni fuori della chiesa e impartire le benedizioni solenni fuori della chiesa;</p>
<p>7) celebrare l'Eucaristia più solenne nelle domeniche e nelle feste di precetto.</p>
<p><strong>Can. 531</strong> - Anche se è un altro a svolgere qualche incarico parrocchiale, le offerte ricevute dai fedeli in tale occasione siano versate nel fondo parrocchiale, a meno che, quando si tratta di offerte volontarie, non consti l'intenzione contraria dell'offerente; spetta al Vescovo diocesano, sentito il consiglio presbiterale, stabilire le norme con le quali si provvede alla destinazione di tali offerte e la rimunerazione dei chierici che svolgono il medesimo incarico.</p>
<p><strong>Can. 532</strong> - Il parroco rappresenta la parrocchia, a norma del diritto, in tutti i negozi giuridici; curi che i beni della parrocchia siano amministrati a norma dei cann. 1281-1288.</p>
<p><strong>Can. 533</strong> - §1. Il parroco è tenuto all'obbligo di risiedere nella casa parrocchiale in vicinanza della chiesa; tuttavia in casi particolari, per giusta causa, l'Ordinario del luogo può permettere che dimori altrove, soprattutto se si tratta di un'abitazione comune a più presbiteri, purché si sia provveduto in modo opportuno e adeguato all'adempimento degli incarichi parrocchiali.</p>
<p>§2. A meno che non sussista un motivo grave, il parroco può assentarsi ogni anno dalla parrocchia per ferie al massimo per un mese, continuo o interrotto; in questo tempo delle ferie non vengono computati i giorni che il parroco dedica una volta all'anno al ritiro spirituale; tuttavia, per assentarsi dalla parrocchia per un tempo superiore ad una settimana, il parroco è tenuto ad avvertirne l'Ordinario del luogo.</p>
<p>§3. Spetta al Vescovo diocesano stabilire norme che assicurino, durante l'assenza del parroco, l'esercizio della cura pastorale della parrocchia tramite un sacerdote fornito delle debite facoltà.</p>
<p><strong>Can. 534</strong> - §1. Dopo aver preso possesso della parrocchia, il parroco è tenuto all'obbligo di applicare la Messa per il popolo affidatogli ogni domenica e nelle feste che nella sua diocesi sono di precetto; chi ne è legittimamente impedito la applichi negli stessi giorni mediante un altro oppure, in giorni diversi, la applichi personalmente.</p>
<p>§2. Il parroco che ha la cura di più parrocchie, nei giorni di cui al §1, è tenuto ad applicare una sola Messa per tutto il popolo affidatogli.</p>
<p>§3. Il parroco che non abbia soddisfatto all'obbligo di cui nei §§1 e 2, applichi quanto prima tante Messe per il popolo quante ne ha tralasciate.</p>
<p><strong>Can. 535</strong> - §1. In ogni parrocchia vi siano i libri parrocchiali, cioè il libro dei battezzati, dei matrimoni, dei defunti ed eventualmente altri libri secondo le disposizioni date dalla Conferenza Episcopale o dal Vescovo diocesano; il parroco provveda che tali libri siano redatti accuratamente e diligentemente conservati.</p>
<p>§2. Nel libro dei battezzati si annoti anche l'ascrizione a una Chiesa sui iuris o il passaggio ad altra Chiesa, nonché la confermazione e tutto ciò che riguarda lo stato canonico dei fedeli, in rapporto al matrimonio, salvo il disposto del can. 1133, all'adozione, all'ordine sacro e alla professione perpetua emessa in un istituto religioso; tali annotazioni vengano sempre riportate nei certificati di battesimo.</p>
<p>§3. Ogni parrocchia abbia il proprio sigillo; gli attestati emessi sullo stato canonico dei fedeli, come pure tutti gli atti che possono avere rilevanza giuridica, siano sottoscritti dal parroco o da un suo delegato e muniti del sigillo parrocchiale.</p>
<p>§4. In ogni parrocchia vi sia il tabularium o archivio, in cui vengano custoditi i libri parrocchiali, insieme con le lettere dei Vescovi e gli altri documenti che si devono conservare per la loro necessità o utilità; tali libri e documenti devono essere controllati dal Vescovo diocesano o dal suo delegato durante la visita o in altro tempo opportuno e il parroco faccia attenzione che essi non vadano in mano ad estranei.</p>
<p>§5. Anche i libri parrocchiali più antichi vengano custoditi diligentemente, secondo le disposizioni del diritto particolare.</p>
<p><strong>Can. 536</strong> - §1. Se risulta opportuno a giudizio del Vescovo diocesano, dopo aver sentito il consiglio presbiterale, in ogni parrocchia venga costituito il consiglio pastorale, che è presieduto dal parroco e nel quale i fedeli, insieme con coloro che partecipano alla cura pastorale della parrocchia in forza del proprio ufficio, prestano il loro aiuto nel promuovere l'attività pastorale.</p>
<p>§2. Il consiglio pastorale ha solamente voto consultivo ed è retto dalle norme stabilite dal Vescovo diocesano.</p>
<p><strong>Can. 537</strong> - In ogni parrocchia vi sia il consiglio per gli affari economici che è retto, oltre che dal diritto universale, dalle norme date dal Vescovo diocesano; in esso i fedeli, scelti secondo le medesime norme, aiutino il parroco nell'amministrazione dei beni della parrocchia, fermo restando il disposto del can. 532.</p>
<p><strong>Can. 538</strong> - §1. Il parroco cessa dall'ufficio con la rimozione o il trasferimento deciso da parte del Vescovo diocesano a norma del diritto, con la rinuncia fatta dal parroco stesso per giusta causa, la quale, per essere valida, deve essere accettata dal Vescovo, e inoltre cessa allo scadere del tempo se fu costituito a tempo determinato, secondo le disposizioni del diritto particolare di cui al can. 522.</p>
<p>§2. Il parroco membro di un istituto religioso o incardinato in una società di vita apostolica, viene rimosso a norma del can. 682, §2.</p>
<p>§3. Compiuti i settantacinque anni, il parroco è invitato a presentare la rinuncia all'ufficio al Vescovo diocesano, il quale, considerata ogni circostanza di persona e di luogo, decida se accettarla o differirla; il Vescovo diocesano deve provvedere in modo adeguato al sostentamento e all'abitazione del rinunciante, attese le norme emanate dalla Conferenza Episcopale.</p>
<p><strong>Can. 539</strong> - Quando la parrocchia è vacante, oppure quando il parroco è impedito nell'esercizio dell'ufficio pastorale nella parrocchia per prigionia, esilio o confino, per inabilità o malferma salute oppure per altre cause, il Vescovo diocesano designi quanto prima l'amministratore parrocchiale, il sacerdote cioè che supplisca il parroco a norma del can. 540.</p>
<p><strong>Can. 540</strong> - §1. L'amministratore parrocchiale è tenuto agli stessi doveri e ha gli stessi diritti del parroco, a meno che il Vescovo diocesano non stabilisca diversamente.</p>
<p>§2. All'amministratore parrocchiale non è lecito compiere nulla che rechi pregiudizio ai diritti del parroco o che possa essere di danno ai beni parrocchiali.</p>
<p>§3. Al termine del suo incarico, l'amministratore parrocchiale presenti al parroco il rendiconto.</p>
<p><strong>Can. 541</strong> - §1. Quando la parrocchia diviene vacante e quando il parroco è impedito nell'esercizio della funzione pastorale, prima della costituzione dell'amministratore parrocchiale, assuma interinalmente il governo della parrocchia il vicario parrocchiale; se essi sono più d'uno, il più anziano per nomina; se poi mancano i vicari, lo assuma il parroco che è indicato dal diritto particolare.</p>
<p>§2. Chi assume il governo della parrocchia a norma del §1, avverta immediatamente l'Ordinario del luogo che la parrocchia è vacante.</p>
<p><strong>Can. 542</strong> - I sacerdoti ai quali, a norma del can. 517, §1, viene affidata in solido la cura pastorale di una parrocchia o di più parrocchie contemporaneamente:</p>
<p>1) devono possedere le qualità di cui al can. 521;</p>
<p>2) siano nominati o istituiti a norma di quanto dispongono i cann. 522 e 524;</p>
<p>3) ottengono la cura pastorale solo dal momento della presa di possesso il loro moderatore viene immesso in possesso a norma di quanto prescrive il can. 527, §2; per gli altri sacerdoti poi la professione di fede emessa legittimamente tiene il posto della presa di possesso.</p>
<p><strong>Can. 543</strong> - §1. Se a determinati sacerdoti viene affidata in solido la cura pastorale di una parrocchia o di più parrocchie contemporaneamente essi sono tenuti singolarmente, secondo l'ordinamento da loro stessi stabilito, all'obbligo di adempiere i compiti e le funzioni proprie del parroco di cui nei cann. 528, 529 e 530; la facoltà di assistere ai matrimoni come pure le facoltà di dispensa concesse al parroco per il diritto stesso, spettano a tutti, ma devono essere esercitate sotto la direzione del moderatore.</p>
<p>§2. Tutti i sacerdoti del gruppo:</p>
<p>1) sono tenuti all'obbligo della residenza;</p>
<p>2) di comune accordo stabiliscano l'ordine secondo cui uno di loro celebra la Messa per il popolo, a norma del can. 533;</p>
<p>3) solo il moderatore rappresenta nei negozi giuridici la parrocchia o le parrocchie affidate al gruppo.</p>
<p><strong>Can. 544</strong> - Quando cessa dall'ufficio un sacerdote del gruppo di cui nel can. 517, §1, o il moderatore del gruppo, e parimenti quando uno di loro diviene inabile ad esercitare la funzione pastorale, non diviene vacante la parrocchia o le parrocchie la cui cura è affidata al gruppo; spetta al Vescovo diocesano nominare un altro moderatore; però prima che il Vescovo costituisca un altro moderatore, adempia tale ufficio il sacerdote del gruppo più anziano per nomina.</p>
<p><strong>Can. 545</strong> - §1. Ogni volta che risulta necessario o opportuno ai fini della adeguata cura pastorale della parrocchia, al parroco possono essere affiancati uno o più vicari parrocchiali, i quali si dedicano al ministero pastorale come cooperatori del parroco e partecipi della sua sollecitudine, mediante attività e iniziative programmate con il parroco e sotto la sua autorità.</p>
<p>§2. Il vicario parrocchiale può essere costituito perché presti il suo aiuto nell'adempiere tutto il ministero pastorale e, in questo caso, o per tutta la parrocchia o per una parte determinata di essa o per un certo gruppo di fedeli; oppure può anche essere costituito per assolvere uno specifico ministero contemporaneamente in più parrocchie determinate.</p>
<p><strong>Can. 546</strong> - Perché uno sia validamente nominato vicario parrocchiale, è necessario che sia costituito nel sacro ordine del presbiterato.</p>
<p><strong>Can. 547</strong> - Il vicario parrocchiale è nominato liberamente dal Vescovo diocesano, dopo aver sentito, se lo ritiene opportuno, il parroco o i parroci delle parrocchie per le quali è costituito, e inoltre il vicario foraneo, fermo restando il disposto del can. 682, §1.</p>
<p><strong>Can. 548</strong> - §1. Gli obblighi e i diritti del vicario parrocchiale sono definiti, oltre che dai canoni del presente capitolo, anche dagli statuti diocesani come pure dalla lettera del Vescovo diocesano, ma sono determinati in modo più specifico dalle disposizioni del parroco.</p>
<p>§2. A meno che nella lettera del Vescovo diocesano non si disponga espressamente altro, il vicario parrocchiale è tenuto all'obbligo, per l'ufficio che esercita, di aiutare il parroco in tutto il ministero parrocchiale, fatta eccezione per quanto riguarda l'applicazione della Messa per il popolo; è anche tenuto all'obbligo di supplirlo, quando è il caso, a norma del diritto.</p>
<p>§3. Il vicario parrocchiale riferisca regolarmente al parroco le iniziative pastorali programmate e in atto, in modo che il parroco e il vicario o i vicari siano in grado di provvedere, con impegno comune, alla cura pastorale della parrocchia, di cui insieme sono garanti.</p>
<p><strong>Can. 549</strong> - Se il parroco è assente, a meno che il Vescovo diocesano non abbia provveduto in modo diverso a norma del can. 533, §3 e a meno che non sia stato costituito l'amministratore parrocchiale, si osservino le disposizioni del can. 541, §1; in tal caso il vicario è tenuto anche a tutti gli obblighi del parroco, fatta eccezione per l'obbligo di applicare la Messa per il popolo.</p>
<p><strong>Can. 550</strong> - §1. Il vicario parrocchiale è tenuto all'obbligo di risiedere nella parrocchia oppure, se è stato costituito per più parrocchie contemporaneamente, di risiedere in una di esse; tuttavia, per una giusta causa, l'Ordinario del luogo può permettere che risieda altrove, soprattutto se si tratta di una casa comune per più presbiteri, purché ciò non rechi pregiudizio all'adempimento delle funzioni pastorali.</p>
<p>§2. L'Ordinario del luogo curi che si promuova, fra parroco e vicari, dove è possibile, una certa pratica di vita comune nella casa parrocchiale.</p>
<p>§3. Per quanto riguarda il periodo delle vacanze, il vicario parrocchiale ha gli stessi diritti del parroco.</p>
<p><strong>Can. 551</strong> - Per quanto riguarda le offerte che i fedeli fanno al vicario in occasione del ministero pastorale, si osservino le disposizioni del can. 531.</p>
<p><strong>Can. 552</strong> - Il vicario parrocchiale può essere rimosso, per giusta causa, dal Vescovo diocesano o dall'Amministratore diocesano, fermo restando il disposto del can. 682, §2.</p>
<p><em>[Redazione originaria dell'articolo modificato da Sua Santità Papa Francesco (cfr. Lettera Apostolica in forma di Motu Proprio "De concordia inter Codices" del 31 maggio 2016)]:</em></p>
<p><strong>Can. 535</strong> - §2. Nel libro dei battezzati si annoti anche la confermazione e tutto ciò che riguarda lo stato canonico dei fedeli, in rapporto al matrimonio, salvo il disposto del can. 1133, all'adozione, come pure in rapporto all'ordine sacro, alla professione perpetua emessa in un istituto religioso e al cambiamento del rito; tali annotazioni vengano sempre riportate nei certificati di battesimo.</p>
`.trim();
