// Stradario del territorio parrocchiale, suddiviso per contrada.
// Caricato da seed-contenuti.ts (npm run seed:contenuti), upsert per via.

export interface SeedStrada {
  contrada: string;
  via: string;
}

export const STRADARIO_SEED: SeedStrada[] = [
  { contrada: 'La Contessa', via: 'Via Filetto' },
  { contrada: 'La Contessa', via: 'Via Oricola' },
  { contrada: 'La Contessa', via: 'Via Fratel Mario Adani' },
  { contrada: 'La Contessa', via: 'Via Riserva Nuova da 1 a 160' },
  { contrada: 'La Contessa', via: 'Via Collecorvino' },
  { contrada: 'La Contessa', via: 'Via Frisa' },
  { contrada: 'La Contessa', via: 'Via Pietranico' },
  { contrada: 'La Contessa', via: 'Via Gessopalena' },
  { contrada: 'La Contessa', via: 'Via Roccaspinalveti' },
  { contrada: 'La Contessa', via: 'Via Torricella Sicura' },
  { contrada: 'La Contessa', via: 'Via don Pirro Scavizzi' },
  { contrada: 'La Contessa', via: 'Via Gamberale' },

  { contrada: 'Il Mericaio', via: 'Via Bellante' },
  { contrada: 'Il Mericaio', via: 'Via Borrello' },
  { contrada: 'Il Mericaio', via: 'Via Colledara' },
  { contrada: 'Il Mericaio', via: 'Via Lucito' },
  { contrada: 'Il Mericaio', via: 'Via Duronia' },
  { contrada: 'Il Mericaio', via: 'Via Furci' },
  { contrada: 'Il Mericaio', via: 'Via Gissi' },
  { contrada: 'Il Mericaio', via: 'Via Lentella' },
  { contrada: 'Il Mericaio', via: 'Via Mafalda' },
  { contrada: 'Il Mericaio', via: 'Via Montalapiano' },
  { contrada: 'Il Mericaio', via: 'Via Palena' },
  { contrada: 'Il Mericaio', via: 'Via Rapino' },
  { contrada: 'Il Mericaio', via: 'Via Rocca di Botte' },
  { contrada: 'Il Mericaio', via: 'Via Rocca Vivara' },
  { contrada: 'Il Mericaio', via: 'Via Sessano del Molise' },
  { contrada: 'Il Mericaio', via: 'Via Vastogirardi' },
  { contrada: 'Il Mericaio', via: 'Via Canosa Sannita' },
  { contrada: 'Il Mericaio', via: 'Via Castel Frentano' },
  { contrada: 'Il Mericaio', via: 'Via Cupello' },
  { contrada: 'Il Mericaio', via: "Via Massa D'albe" },
  { contrada: 'Il Mericaio', via: 'Via Montazzoli' },
  { contrada: 'Il Mericaio', via: 'Via Roio del Sangro' },
  { contrada: 'Il Mericaio', via: 'Via Montefino' },
  { contrada: 'Il Mericaio', via: 'Via della Riserva nuova da 162 a 298' },
  { contrada: 'Il Mericaio', via: 'Via Pescolanciano' },
  { contrada: 'Il Mericaio', via: 'Via Bagnoli del Trigno' },
  { contrada: 'Il Mericaio', via: 'Via Bucchianico' },
  { contrada: 'Il Mericaio', via: 'Via Casacanditella' },
  { contrada: 'Il Mericaio', via: 'Via Casalanguida' },
  { contrada: 'Il Mericaio', via: 'Via Castemauro' },
  { contrada: 'Il Mericaio', via: 'Via Cermignano' },
  { contrada: 'Il Mericaio', via: 'Via Crecchio' },
  { contrada: 'Il Mericaio', via: 'Via Fontecchio' },
  { contrada: 'Il Mericaio', via: 'Via Lettopalena' },
  { contrada: 'Il Mericaio', via: 'Via Montemitro' },
  { contrada: 'Il Mericaio', via: 'Via Pietrabbondante' },
  { contrada: 'Il Mericaio', via: 'Via Del Fosso Scilicino' },
  { contrada: 'Il Mericaio', via: 'Via Fosso dell\'Osa da 421 ad 1' },
  { contrada: 'Il Mericaio', via: 'Via Merignano' },
  { contrada: 'Il Mericaio', via: 'Via Montagamo' },
  { contrada: 'Il Mericaio', via: 'Via Pereto' },
  { contrada: 'Il Mericaio', via: 'Via Roccacasale' },

  { contrada: "L'Ovile", via: 'Via Pennadomo' },
  { contrada: "L'Ovile", via: 'Via Guardalfiera' },
  { contrada: "L'Ovile", via: 'Via Cardinale Federico Tedeschini' },
  { contrada: "L'Ovile", via: 'Via Castel di Sangro' },
  { contrada: "L'Ovile", via: 'Via Fara S. MArtino' },
  { contrada: "L'Ovile", via: 'Via Montagnano' },
  { contrada: "L'Ovile", via: "Via Fosso dell'Osa da 549 a 423" },
  { contrada: "L'Ovile", via: 'Via Montaquila' },
  { contrada: "L'Ovile", via: 'Via Cugnoli' },
  { contrada: "L'Ovile", via: 'Via Larino' },
  { contrada: "L'Ovile", via: 'Via Macchiogodena' },
  { contrada: "L'Ovile", via: 'Via Perano' },
  { contrada: "L'Ovile", via: 'Via Tollo' },
  { contrada: "L'Ovile", via: 'Via Pizzoferrato' },
  { contrada: "L'Ovile", via: 'Via Pollutri' },
  { contrada: "L'Ovile", via: "Via Schiavi d'Abruzzo" },
  { contrada: "L'Ovile", via: 'Largo Scapoli' },

  { contrada: 'Le Botti', via: 'Via Acciano' },
  { contrada: 'Le Botti', via: 'Via Aielli' },
  { contrada: 'Le Botti', via: 'Via Ateleta' },
  { contrada: 'Le Botti', via: 'Via Barete' },
  { contrada: 'Le Botti', via: 'Via Bugnara' },
  { contrada: 'Le Botti', via: 'Via Busso' },
  { contrada: 'Le Botti', via: 'Via Canzano' },
  { contrada: 'Le Botti', via: 'Via Crognaleto' },
  { contrada: 'Le Botti', via: "Via Fosso Dell'Osa da 550 a 691" },
  { contrada: 'Le Botti', via: 'Via Notaresco' },
  { contrada: 'Le Botti', via: 'Via Rocca di Cambio' },
  { contrada: 'Le Botti', via: 'Via Sepino' },
  { contrada: 'Le Botti', via: 'Via Treglio' },
  { contrada: 'Le Botti', via: 'Via Villamagna' },
  { contrada: 'Le Botti', via: 'Via Vinchiaturo' },
  { contrada: 'Le Botti', via: 'Via Balsorano' },
  { contrada: 'Le Botti', via: 'via Elice' },
  { contrada: 'Le Botti', via: 'Via Guglioresi' },
  { contrada: 'Le Botti', via: 'Via Carpinone' },
];
